/*
Source file for OpenMC generated by MCNP_to_OpenMC.py script by Max Conroy.    

Distributions based on MCNP SDEF file by Daniel Minsky.    

Details:
	Generated on 13-02-2024.    

For more information, please contact m.j.conroy@pgr.bham.ac.uk.
*/
#include <memory>
#include <cmath>
#include <vector>
#include <iostream>
#include "openmc/random_lcg.h"
#include "openmc/source.h"
#include "openmc/particle.h"
#include "openmc/distribution.h"

// Create new source class which inherits from openmc::Source    
class Li_source : public openmc::Source {

	// Define a function called "sample" to generate neutrons
	openmc::SourceSite sample(uint64_t* seed) const {

		openmc::SourceSite particle;
		// Define particle type
		particle.particle = openmc::ParticleType::neutron;    
		// Define particle weight
		particle.wgt = 1.626763e+11;

		// Initialise required variables    
		double energy {0.0};
		double mu {0.0};    
		double theta {0.0};
		double phi {0.0};    
		double pos_r {0.0};
		double pos_ang {0.0};

		// Define energies and probabilities for distribution    
		double energies[134] = {     0.,  1000.,  2000.,  3000.,  5000.,  7000., 12000., 19000., 24000.,
  30000., 33000., 36000., 58000., 83000., 88000., 90000.,101000.,110000.,
 112000.,119000.,121000.,124000.,126000.,129000.,131000.,134000.,136000.,
 137000.,138000.,139000.,144000.,147000.,152000.,153000.,155000.,158000.,
 160000.,161000.,163000.,164000.,166000.,167000.,169000.,170000.,172000.,
 175000.,177000.,178000.,180000.,181000.,183000.,184000.,186000.,187000.,
 189000.,190000.,192000.,193000.,195000.,196000.,198000.,199000.,201000.,
 202000.,204000.,205000.,206000.,207000.,209000.,210000.,212000.,213000.,
 215000.,216000.,218000.,219000.,221000.,222000.,223000.,224000.,226000.,
 227000.,229000.,230000.,232000.,233000.,234000.,235000.,237000.,238000.,
 240000.,241000.,242000.,243000.,245000.,246000.,247000.,248000.,249000.,
 250000.,252000.,253000.,254000.,255000.,256000.,257000.,259000.,260000.,
 261000.,262000.,263000.,264000.,265000.,266000.,267000.,268000.,269000.,
 270000.,271000.,273000.,274000.,275000.,276000.,278000.,279000.,282000.,
 283000.,285000.,286000.,288000.,289000.,290000.,291000.,292000.};    
		double E_probabilities[134] = {0.00000000e+00,5.67168836e-03,8.04259799e-03,9.86033007e-03,
 1.27251016e-02,1.50273117e-02,1.95383379e-02,2.42395977e-02,
 2.68519554e-02,2.92978822e-02,3.00918320e-02,2.98524779e-02,
 2.66790741e-02,2.21308819e-02,2.15549381e-02,2.09590524e-02,
 1.93744849e-02,1.77186280e-02,1.76840352e-02,1.63334621e-02,
 1.62948543e-02,1.56222985e-02,1.55792750e-02,1.49083200e-02,
 1.48580303e-02,1.41753506e-02,1.41210839e-02,1.37936908e-02,
 1.37659421e-02,1.34403774e-02,1.30041710e-02,1.23339986e-02,
 1.19051865e-02,1.15899140e-02,1.15349264e-02,1.08853740e-02,
 1.08305216e-02,1.05242133e-02,1.04701482e-02,1.01671339e-02,
 1.01140814e-02,9.81463391e-03,9.76277425e-03,9.46713534e-03,
 9.41660609e-03,8.81308901e-03,8.76438818e-03,8.48165726e-03,
 8.43447417e-03,8.15622062e-03,8.11055292e-03,7.83690004e-03,
 7.79273112e-03,7.52378090e-03,7.48107518e-03,7.21691063e-03,
 7.17561357e-03,6.91630819e-03,6.87634865e-03,6.62195936e-03,
 6.58325197e-03,6.33381908e-03,6.29628794e-03,6.05186838e-03,
 6.01547793e-03,5.77613334e-03,5.75831874e-03,5.52428154e-03,
 5.48946101e-03,5.26063634e-03,5.22704898e-03,5.00352932e-03,
 4.97125814e-03,4.75313124e-03,4.72226161e-03,4.50960810e-03,
 4.48021116e-03,4.27309981e-03,4.25897050e-03,4.05744874e-03,
 4.03039008e-03,3.83449824e-03,3.80906405e-03,3.61884242e-03,
 3.59505642e-03,3.41052161e-03,3.39926180e-03,3.22034030e-03,
 3.19907993e-03,3.02582392e-03,3.00612872e-03,2.83849550e-03,
 2.82922299e-03,2.66708924e-03,2.64963274e-03,2.49301506e-03,
 2.48480024e-03,2.33358291e-03,2.32572452e-03,2.17985917e-03,
 2.16513129e-03,2.02466984e-03,2.01779775e-03,1.88262210e-03,
 1.87611973e-03,1.74619574e-03,1.73423372e-03,1.60966360e-03,
 1.60422175e-03,1.48485941e-03,1.47983850e-03,1.36565193e-03,
 1.36106785e-03,1.25202385e-03,1.24789129e-03,1.14395571e-03,
 1.14028868e-03,1.04142689e-03,1.03823842e-03,8.55383106e-04,
 8.52895417e-04,7.68816519e-04,7.66824234e-04,6.13084597e-04,
 6.11767711e-04,4.15817997e-04,4.15246232e-04,3.06880710e-04,
 2.59095032e-04,1.76022829e-04,1.09242071e-04,8.18519781e-05,
 3.89191191e-05,0.00000000e+00};
		// Define energy distribution
		openmc::Tabular E_dist(energies, E_probabilities, 134, openmc::Interpolation::lin_lin);
		// Sample energy from distribution
		energy = E_dist.sample(seed);
		particle.E = energy;

		// Define energy values for bin edges to choose angular distribution    
		double edges[73] = {  5000.,  9000., 13000., 17000., 21000., 25000., 29000., 33000., 37000.,
  41000., 45000., 49000., 53000., 57000., 61000., 65000., 69000., 73000.,
  77000., 81000., 85000., 89000., 93000., 97000.,101000.,105000.,109000.,
 113000.,117000.,121000.,125000.,129000.,133000.,137000.,141000.,145000.,
 149000.,153000.,157000.,161000.,165000.,169000.,173000.,177000.,181000.,
 185000.,189000.,193000.,197000.,201000.,205000.,209000.,213000.,217000.,
 221000.,225000.,229000.,233000.,237000.,241000.,245000.,249000.,253000.,
 257000.,261000.,265000.,269000.,273000.,277000.,281000.,285000.,289000.,
 292000.};

		// Create vector to hold angular distributions        
		std::vector<openmc::Tabular> ang_dists;

		// Angular distribution for energies 0.0 < E <= 5000.0            
		double cos_angles_1[6] = {-1.       ,-0.052336 ,-0.0348995, 0.515038 , 0.766044 , 1.       };            
		double ang_probabilities_1[6] = {0.13454542,0.15214883,0.1478466 ,0.17108408,0.1870698 ,0.20730527};            
		openmc::Tabular ang_dist_1(cos_angles_1, ang_probabilities_1, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_1);

		// Angular distribution for energies 5000.0 < E <= 9000.0            
		double cos_angles_2[9] = {-1.      ,-0.358368, 0.104528, 0.121869, 0.374607, 0.601815, 0.809017,
  0.906308, 1.      };            
		double ang_probabilities_2[9] = {0.07824939,0.08623586,0.09513689,0.09266001,0.10218601,0.11458028,
 0.13148015,0.14265184,0.15681957};            
		openmc::Tabular ang_dist_2(cos_angles_2, ang_probabilities_2, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_2);

		// Angular distribution for energies 9000.0 < E <= 13000.0            
		double cos_angles_3[11] = {-1.      ,-0.601815,-0.139173, 0.190809, 0.207912, 0.438371, 0.656059,
  0.75471 , 0.838671, 0.927184, 1.      };            
		double ang_probabilities_3[11] = {0.06040601,0.06180932,0.06806523,0.07454513,0.07268065,0.08155196,
 0.09461814,0.10320713,0.11278949,0.12669271,0.14363425};            
		openmc::Tabular ang_dist_3(cos_angles_3, ang_probabilities_3, 11, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_3);

		// Angular distribution for energies 13000.0 < E <= 17000.0            
		double cos_angles_4[14] = {-1.      ,-0.642788,-0.469472,-0.052336, 0.258819, 0.275637, 0.5     ,
  0.601815, 0.694658, 0.788011, 0.866025, 0.939693, 0.970296, 1.      };            
		double ang_probabilities_4[14] = {0.04428786,0.04432437,0.04502328,0.04972589,0.05496835,0.05367896,
 0.06147388,0.06655697,0.07256619,0.08067927,0.0901531 ,0.10345174,
 0.11137646,0.12173368};            
		openmc::Tabular ang_dist_4(cos_angles_4, ang_probabilities_4, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_4);

		// Angular distribution for energies 17000.0 < E <= 21000.0            
		double cos_angles_5[14] = {-1.       ,-0.374607 , 0.0174524, 0.309017 , 0.325568 , 0.529919 ,
  0.62932  , 0.71934  , 0.809017 , 0.882948 , 0.920505 , 0.951057 ,
  0.978148 , 1.       };            
		double ang_probabilities_5[14] = {0.03990272,0.04011931,0.04444427,0.04943686,0.04827009,0.05552168,
 0.06067785,0.06690758,0.07557226,0.08613356,0.09375038,0.10204363,
 0.11231831,0.12490148};            
		openmc::Tabular ang_dist_5(cos_angles_5, ang_probabilities_5, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_5);

		// Angular distribution for energies 21000.0 < E <= 25000.0            
		double cos_angles_6[17] = {-1.       ,-0.731354 ,-0.292372 ,-0.0348995, 0.156434 , 0.358368 ,
  0.374607 , 0.573576 , 0.669131 , 0.75471  , 0.838671 , 0.906308 ,
  0.93358  , 0.961262 , 0.984808 , 0.992546 , 1.       };            
		double ang_probabilities_6[17] = {0.03169453,0.03093019,0.03124084,0.03337422,0.03565515,0.03883935,
 0.03797669,0.04429153,0.04885833,0.05446193,0.06243058,0.07247867,
 0.078426  ,0.0867924 ,0.09794333,0.10350369,0.11110257};            
		openmc::Tabular ang_dist_6(cos_angles_6, ang_probabilities_6, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_6);

		// Angular distribution for energies 25000.0 < E <= 29000.0            
		double cos_angles_7[20] = {-1.       ,-0.601815 ,-0.207912 , 0.0348995, 0.207912 , 0.390731 ,
  0.406737 , 0.5      , 0.601815 , 0.694658 , 0.777146 , 0.857167 ,
  0.891007 , 0.920505 , 0.945519 , 0.970296 , 0.981627 , 0.990268 ,
  0.996195 , 1.       };            
		double ang_probabilities_7[20] = {0.02494149,0.02436464,0.02463899,0.02637101,0.02816218,0.03069123,
 0.02993536,0.03212048,0.03525665,0.0391538 ,0.04398856,0.05097295,
 0.05519317,0.0600044 ,0.0655054 ,0.07352605,0.07903507,0.0850939 ,
 0.09158228,0.09946239};            
		openmc::Tabular ang_dist_7(cos_angles_7, ang_probabilities_7, 20, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_7);

		// Angular distribution for energies 29000.0 < E <= 33000.0            
		double cos_angles_8[22] = {-1.       ,-0.777146 ,-0.5      ,-0.139173 , 0.0871557, 0.258819 ,
  0.438371 , 0.45399  , 0.544639 , 0.62932  , 0.71934  , 0.798636 ,
  0.866025 , 0.898794 , 0.927184 , 0.951057 , 0.97437  , 0.984808 ,
  0.992546 , 0.997564 , 0.999391 , 1.       };            
		double ang_probabilities_8[22] = {0.02156424,0.02172235,0.02117634,0.02142946,0.02291359,0.0246025 ,
 0.0269432 ,0.02637663,0.02844925,0.03096794,0.03458313,0.03909581,
 0.04474885,0.04861829,0.05305473,0.05816316,0.06569414,0.07094269,
 0.07682636,0.08336945,0.0879134 ,0.09084448};            
		openmc::Tabular ang_dist_8(cos_angles_8, ang_probabilities_8, 22, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_8);

		// Angular distribution for energies 33000.0 < E <= 37000.0            
		double cos_angles_9[22] = {-0.93358  ,-0.927184 ,-0.857167 ,-0.669131 ,-0.422618 ,-0.0871557,
  0.121869 , 0.309017 , 0.469472 , 0.48481  , 0.573576 , 0.656059 ,
  0.731354 , 0.798636 , 0.866025 , 0.898794 , 0.927184 , 0.951057 ,
  0.970296 , 0.987688 , 0.994522 , 1.       };            
		double ang_probabilities_9[22] = {0.        ,0.02612326,0.02572968,0.02598937,0.02536355,0.02565628,
 0.02729555,0.02968319,0.03242326,0.03170797,0.03431404,0.03748878,
 0.04133878,0.04600044,0.05270426,0.05727971,0.06250117,0.06846232,
 0.0752468 ,0.08487274,0.09096877,0.09885009};            
		openmc::Tabular ang_dist_9(cos_angles_9, ang_probabilities_9, 22, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_9);

		// Angular distribution for energies 37000.0 < E <= 41000.0            
		double cos_angles_10[20] = {-0.829038 ,-0.819152 ,-0.75471  ,-0.573576 ,-0.34202  ,-0.0174524,
  0.190809 , 0.34202  , 0.5      , 0.515038 , 0.669131 , 0.743145 ,
  0.809017 , 0.866025 , 0.920505 , 0.945519 , 0.965926 , 0.984808 ,
  0.992546 , 1.       };            
		double ang_probabilities_10[20] = {0.        ,0.02972367,0.02930381,0.02960055,0.02891422,0.02934146,
 0.03149213,0.03386655,0.03716926,0.03632797,0.04253121,0.04697116,
 0.05233725,0.05881197,0.06805228,0.07426349,0.08116931,0.09052484,
 0.09606697,0.10353189};            
		openmc::Tabular ang_dist_10(cos_angles_10, ang_probabilities_10, 20, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_10);

		// Angular distribution for energies 41000.0 < E <= 45000.0            
		double cos_angles_11[19] = {-0.731354 ,-0.71934  ,-0.656059 ,-0.48481  ,-0.275637 , 0.0348995,
  0.224951 , 0.374607 , 0.529919 , 0.544639 , 0.681998 , 0.743145 ,
  0.809017 , 0.866025 , 0.920505 , 0.945519 , 0.965926 , 0.984808 ,
  1.       };            
		double ang_probabilities_11[19] = {0.        ,0.03361228,0.03321381,0.03355193,0.03281354,0.03335029,
 0.03567013,0.03850632,0.04243947,0.04147159,0.04800911,0.05215646,
 0.05805909,0.06512918,0.07506717,0.0816019 ,0.08867084,0.09776868,
 0.10890821};            
		openmc::Tabular ang_dist_11(cos_angles_11, ang_probabilities_11, 19, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_11);

		// Angular distribution for energies 45000.0 < E <= 49000.0            
		double cos_angles_12[18] = {-0.656059 ,-0.642788 ,-0.587785 ,-0.422618 ,-0.207912 , 0.0871557,
  0.275637 , 0.422618 , 0.559193 , 0.573576 , 0.707107 , 0.766044 ,
  0.819152 , 0.87462  , 0.920505 , 0.965926 , 0.984808 , 1.       };            
		double ang_probabilities_12[18] = {0.        ,0.03730345,0.0367925 ,0.03717241,0.03636462,0.03704979,
 0.03985346,0.04320495,0.04734866,0.0462763 ,0.05377119,0.05850048,
 0.06398865,0.07168458,0.08066492,0.0943325 ,0.10297651,0.11271502};            
		openmc::Tabular ang_dist_12(cos_angles_12, ang_probabilities_12, 18, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_12);

		// Angular distribution for energies 49000.0 < E <= 53000.0            
		double cos_angles_13[18] = {-0.573576,-0.559193,-0.5     ,-0.34202 ,-0.156434, 0.139173, 0.309017,
  0.45399 , 0.587785, 0.601815, 0.71934 , 0.777146, 0.829038, 0.882948,
  0.927184, 0.965926, 0.984808, 1.      };            
		double ang_probabilities_13[18] = {0.        ,0.03781123,0.0374003 ,0.03778371,0.0370193 ,0.03783957,
 0.04059551,0.04416172,0.04854538,0.04746638,0.05442237,0.05919892,
 0.06470425,0.07233279,0.08104776,0.09212309,0.09972816,0.10781956};            
		openmc::Tabular ang_dist_13(cos_angles_13, ang_probabilities_13, 18, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_13);

		// Angular distribution for energies 53000.0 < E <= 57000.0            
		double cos_angles_14[18] = {-0.515038,-0.5     ,-0.438371,-0.292372,-0.104528, 0.104528, 0.224951,
  0.34202 , 0.48481 , 0.615661, 0.62932 , 0.694658, 0.788011, 0.866025,
  0.906308, 0.939693, 0.970296, 1.      };            
		double ang_probabilities_14[18] = {0.        ,0.04063106,0.04004129,0.04047991,0.03967014,0.04019104,
 0.04115702,0.0435724 ,0.04755701,0.05241751,0.05128513,0.05527185,
 0.06303176,0.07263786,0.07957169,0.08707089,0.09626561,0.10914782};            
		openmc::Tabular ang_dist_14(cos_angles_14, ang_probabilities_14, 18, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_14);

		// Angular distribution for energies 57000.0 < E <= 61000.0            
		double cos_angles_15[17] = {-0.45399  ,-0.438371 ,-0.374607 ,-0.241922 , 0.0174524, 0.224951 ,
  0.358368 , 0.515038 , 0.642788 , 0.656059 , 0.707107 , 0.788011 ,
  0.866025 , 0.906308 , 0.939693 , 0.970296 , 1.       };            
		double ang_probabilities_15[17] = {0.        ,0.04313105,0.04247542,0.04295549,0.04227097,0.04327863,
 0.04592684,0.05078252,0.05610168,0.05493266,0.05834721,0.06536063,
 0.07505435,0.08195916,0.08931357,0.09812825,0.10998156};            
		openmc::Tabular ang_dist_15(cos_angles_15, ang_probabilities_15, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_15);

		// Angular distribution for energies 61000.0 < E <= 65000.0            
		double cos_angles_16[16] = {-0.390731,-0.374607,-0.325568,-0.190809, 0.052336, 0.241922, 0.374607,
  0.529919, 0.669131, 0.681998, 0.707107, 0.788011, 0.866025, 0.939693,
  0.970296, 1.      };            
		double ang_probabilities_16[16] = {0.        ,0.0476863 ,0.04708098,0.0476116 ,0.04687577,0.04787947,
 0.05059937,0.0560865 ,0.06274709,0.06149271,0.06336892,0.07082727,
 0.08104704,0.09579266,0.10467289,0.11623143};            
		openmc::Tabular ang_dist_16(cos_angles_16, ang_probabilities_16, 16, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_16);

		// Angular distribution for energies 65000.0 < E <= 69000.0            
		double cos_angles_17[15] = {-0.34202  ,-0.325568 ,-0.275637 ,-0.139173 , 0.0697565, 0.275637 ,
  0.390731 , 0.559193 , 0.694658 , 0.707107 , 0.788011 , 0.866025 ,
  0.939693 , 0.970296 , 1.       };            
		double ang_probabilities_17[15] = {0.        ,0.05179904,0.05102264,0.05159072,0.05075559,0.05200994,
 0.05453661,0.06122917,0.06863048,0.06731793,0.0750716 ,0.08561185,
 0.10055755,0.10935628,0.12051059};            
		openmc::Tabular ang_dist_17(cos_angles_17, ang_probabilities_17, 15, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_17);

		// Angular distribution for energies 69000.0 < E <= 73000.0            
		double cos_angles_18[15] = {-0.292372,-0.275637,-0.224951,-0.104528, 0.104528, 0.309017, 0.406737,
  0.587785, 0.71934 , 0.731354, 0.809017, 0.87462 , 0.939693, 0.970296,
  1.      };            
		double ang_probabilities_18[15] = {0.        ,0.05234004,0.05152053,0.05211025,0.05129508,0.05267202,
 0.05481633,0.06233117,0.06997237,0.06869157,0.07658505,0.08570315,
 0.09849404,0.10666565,0.11680276};            
		openmc::Tabular ang_dist_18(cos_angles_18, ang_probabilities_18, 15, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_18);

		// Angular distribution for energies 73000.0 < E <= 77000.0            
		double cos_angles_19[14] = {-0.241922,-0.224951,-0.173648,-0.052336, 0.139173, 0.34202 , 0.438371,
  0.601815, 0.743145, 0.75471 , 0.819152, 0.882948, 0.945519, 1.      };            
		double ang_probabilities_19[14] = {0.        ,0.05887793,0.05801615,0.05869837,0.05782796,0.05951664,
 0.06205642,0.07002493,0.07957885,0.07817847,0.08573685,0.09566431,
 0.10921563,0.12660749};            
		openmc::Tabular ang_dist_19(cos_angles_19, ang_probabilities_19, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_19);

		// Angular distribution for energies 77000.0 < E <= 81000.0            
		double cos_angles_20[12] = {-0.190809,-0.173648, 0.173648, 0.358368, 0.45399 , 0.62932 , 0.766044,
  0.777146, 0.838671, 0.891007, 0.945519, 1.      };            
		double ang_probabilities_20[12] = {0.        ,0.06690788,0.06597374,0.06779887,0.0704567 ,0.08050204,
 0.09157824,0.09001545,0.09860867,0.1080218 ,0.12094563,0.13919097};            
		openmc::Tabular ang_dist_20(cos_angles_20, ang_probabilities_20, 12, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_20);

		// Angular distribution for energies 81000.0 < E <= 85000.0            
		double cos_angles_21[12] = {-0.139173,-0.121869, 0.207912, 0.390731, 0.469472, 0.642788, 0.788011,
  0.798636, 0.857167, 0.906308, 0.956305, 1.      };            
		double ang_probabilities_21[12] = {0.        ,0.06679133,0.06620182,0.06819734,0.07038871,0.08050313,
 0.09267426,0.09112081,0.0996553 ,0.10878941,0.12081795,0.13485994};            
		openmc::Tabular ang_dist_21(cos_angles_21, ang_probabilities_21, 12, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_21);

		// Angular distribution for energies 85000.0 < E <= 89000.0            
		double cos_angles_22[11] = {-0.104528 ,-0.0871557, 0.241922 , 0.422618 , 0.5      , 0.669131 ,
  0.798636 , 0.809017 , 0.906308 , 0.956305 , 1.       };            
		double ang_probabilities_22[11] = {0.        ,0.07512481,0.07435285,0.07679291,0.07943012,0.09112276,
 0.10400493,0.10168173,0.11913347,0.13185856,0.14649785};            
		openmc::Tabular ang_dist_22(cos_angles_22, ang_probabilities_22, 11, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_22);

		// Angular distribution for energies 89000.0 < E <= 93000.0            
		double cos_angles_23[12] = {-0.0697565,-0.052336 ,-0.0174524, 0.104528 , 0.258819 , 0.438371 ,
  0.515038 , 0.681998 , 0.819152 , 0.829038 , 0.920505 , 1.       };            
		double ang_probabilities_23[12] = {0.        ,0.0741447 ,0.07326204,0.07411209,0.07320593,0.0756212 ,
 0.07801848,0.08954401,0.10337519,0.10105473,0.11770092,0.13996071};            
		openmc::Tabular ang_dist_23(cos_angles_23, ang_probabilities_23, 12, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_23);

		// Angular distribution for energies 93000.0 < E <= 97000.0            
		double cos_angles_24[13] = {-0.0348995,-0.0174524, 0.0348995, 0.139173 , 0.292372 , 0.45399  ,
  0.529919 , 0.669131 , 0.743145 , 0.848048 , 0.857167 , 0.927184 ,
  1.       };            
		double ang_probabilities_24[13] = {0.        ,0.06810606,0.0671658 ,0.06799391,0.06724416,0.06937413,
 0.07140907,0.07998062,0.08589412,0.0964979 ,0.0947877 ,0.10681739,
 0.12472913};            
		openmc::Tabular ang_dist_24(cos_angles_24, ang_probabilities_24, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_24);

		// Angular distribution for energies 97000.0 < E <= 101000.0            
		double cos_angles_25[12] = {-1.03634e-13, 1.74524e-02, 6.97565e-02, 1.73648e-01, 3.09017e-01,
  5.44639e-01, 6.81998e-01, 7.66044e-01, 8.66025e-01, 8.74620e-01,
  9.39693e-01, 1.00000e+00};            
		double ang_probabilities_25[12] = {0.        ,0.07333165,0.07228157,0.07318058,0.07236189,0.07671143,
 0.08579165,0.09331896,0.10469826,0.1027261 ,0.1150234 ,0.13057451};            
		openmc::Tabular ang_dist_25(cos_angles_25, ang_probabilities_25, 12, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_25);

		// Angular distribution for energies 101000.0 < E <= 105000.0            
		double cos_angles_26[12] = {0.0348995,0.052336 ,0.0871557,0.190809 ,0.34202  ,0.573576 ,0.707107 ,
 0.788011 ,0.882948 ,0.891007 ,0.945519 ,1.       };            
		double ang_probabilities_26[12] = {0.        ,0.07338832,0.07240642,0.07325801,0.07253648,0.07728721,
 0.08668516,0.0942887 ,0.10560403,0.10344504,0.11379736,0.12730326};            
		openmc::Tabular ang_dist_26(cos_angles_26, ang_probabilities_26, 12, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_26);

		// Angular distribution for energies 105000.0 < E <= 109000.0            
		double cos_angles_27[13] = {0.0697565,0.0871557,0.121869 ,0.224951 ,0.374607 ,0.587785 ,0.642788 ,
 0.71934  ,0.798636 ,0.898794 ,0.906308 ,0.956305 ,1.       };            
		double ang_probabilities_27[13] = {0.        ,0.06805123,0.06718868,0.06801254,0.0674371 ,0.07163437,
 0.07445186,0.08018743,0.08724925,0.09869971,0.0964706 ,0.10541124,
 0.11520601};            
		openmc::Tabular ang_dist_27(cos_angles_27, ang_probabilities_27, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_27);

		// Angular distribution for energies 109000.0 < E <= 113000.0            
		double cos_angles_28[11] = {0.104528,0.121869,0.156434,0.258819,0.390731,0.601815,0.707107,0.819152,
 0.920505,0.927184,1.      };            
		double ang_probabilities_28[11] = {0.        ,0.08301932,0.08207639,0.08312438,0.08239763,0.08744131,
 0.09515949,0.10754106,0.12223212,0.11962427,0.13738404};            
		openmc::Tabular ang_dist_28(cos_angles_28, ang_probabilities_28, 11, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_28);

		// Angular distribution for energies 113000.0 < E <= 117000.0            
		double cos_angles_29[9] = {0.139173,0.156434,0.422618,0.62932 ,0.707107,0.809017,0.939693,0.945519,
 1.      };            
		double ang_probabilities_29[9] = {0.        ,0.09973566,0.0993677 ,0.10596207,0.11275133,0.12614095,
 0.14884908,0.14564125,0.16155195};            
		openmc::Tabular ang_dist_29(cos_angles_29, ang_probabilities_29, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_29);

		// Angular distribution for energies 117000.0 < E <= 121000.0            
		double cos_angles_30[10] = {0.173648,0.190809,0.45399 ,0.642788,0.707107,0.777146,0.857167,0.956305,
 0.961262,1.      };            
		double ang_probabilities_30[10] = {0.        ,0.08867228,0.08873977,0.09435189,0.09899082,0.10667721,
 0.11720772,0.13386864,0.13075211,0.14073956};            
		openmc::Tabular ang_dist_30(cos_angles_30, ang_probabilities_30, 10, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_30);

		// Angular distribution for energies 121000.0 < E <= 125000.0            
		double cos_angles_31[11] = {0.190809,0.207912,0.241922,0.469472,0.656059,0.707107,0.777146,0.87462 ,
 0.97437 ,0.978148,1.      };            
		double ang_probabilities_31[11] = {0.        ,0.08219233,0.08110587,0.08169105,0.08682501,0.08991244,
 0.09658794,0.10865553,0.12466149,0.12160396,0.12676438};            
		openmc::Tabular ang_dist_31(cos_angles_31, ang_probabilities_31, 11, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_31);

		// Angular distribution for energies 125000.0 < E <= 129000.0            
		double cos_angles_32[9] = {0.224951,0.241922,0.48481 ,0.669131,0.777146,0.891007,0.990268,0.992546,
 1.      };            
		double ang_probabilities_32[9] = {0.        ,0.09903682,0.09879441,0.10495996,0.11488202,0.13217896,
 0.15215017,0.14794443,0.15005323};            
		openmc::Tabular ang_dist_32(cos_angles_32, ang_probabilities_32, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_32);

		// Angular distribution for energies 129000.0 < E <= 133000.0            
		double cos_angles_33[9] = {0.241922,0.258819,0.309017,0.515038,0.694658,0.75471 ,0.819152,0.913545,
 1.      };            
		double ang_probabilities_33[9] = {0.        ,0.10857464,0.10679986,0.10780208,0.115025  ,0.12035068,
 0.12933907,0.14607947,0.1660292 };            
		openmc::Tabular ang_dist_33(cos_angles_33, ang_probabilities_33, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_33);

		// Angular distribution for energies 133000.0 < E <= 137000.0            
		double cos_angles_34[9] = {0.275637,0.292372,0.325568,0.529919,0.707107,0.766044,0.829038,0.927184,
 1.      };            
		double ang_probabilities_34[9] = {0.        ,0.1083721 ,0.10709958,0.1081079 ,0.1153021 ,0.12035665,
 0.12909272,0.14696105,0.16470789};            
		openmc::Tabular ang_dist_34(cos_angles_34, ang_probabilities_34, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_34);

		// Angular distribution for energies 137000.0 < E <= 141000.0            
		double cos_angles_35[8] = {0.309017,0.325568,0.559193,0.731354,0.777146,0.838671,0.939693,1.      };            
		double ang_probabilities_35[8] = {0.        ,0.12118084,0.12168565,0.13031857,0.13482119,0.14427984,
 0.16537658,0.18233733};            
		openmc::Tabular ang_dist_35(cos_angles_35, ang_probabilities_35, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_35);

		// Angular distribution for energies 141000.0 < E <= 145000.0            
		double cos_angles_36[9] = {0.325568,0.34202 ,0.374607,0.573576,0.743145,0.798636,0.848048,0.945519,
 1.      };            
		double ang_probabilities_36[9] = {0.        ,0.10909989,0.10774242,0.10897107,0.11664631,0.12163365,
 0.12856593,0.14703647,0.16030427};            
		openmc::Tabular ang_dist_36(cos_angles_36, ang_probabilities_36, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_36);

		// Angular distribution for energies 145000.0 < E <= 149000.0            
		double cos_angles_37[7] = {0.358368,0.374607,0.601815,0.75471 ,0.809017,0.857167,1.      };            
		double ang_probabilities_37[7] = {0.        ,0.14653107,0.14744802,0.15737768,0.16372612,0.17266217,
 0.21225493};            
		openmc::Tabular ang_dist_37(cos_angles_37, ang_probabilities_37, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_37);

		// Angular distribution for energies 149000.0 < E <= 153000.0            
		double cos_angles_38[8] = {0.374607,0.390731,0.422618,0.615661,0.766044,0.819152,0.866025,1.      };            
		double ang_probabilities_38[8] = {0.        ,0.12904546,0.12746814,0.12920088,0.13785126,0.14310756,
 0.15053791,0.1827888 };            
		openmc::Tabular ang_dist_38(cos_angles_38, ang_probabilities_38, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_38);

		// Angular distribution for energies 153000.0 < E <= 157000.0            
		double cos_angles_39[9] = {0.390731,0.406737,0.45399 ,0.62932 ,0.75471 ,0.819152,0.866025,0.920505,
 1.      };            
		double ang_probabilities_39[9] = {0.        ,0.11267893,0.11069975,0.11219974,0.11817338,0.12296811,
 0.12872048,0.13838562,0.15617399};            
		openmc::Tabular ang_dist_39(cos_angles_39, ang_probabilities_39, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_39);

		// Angular distribution for energies 157000.0 < E <= 161000.0            
		double cos_angles_40[9] = {0.422618,0.438371,0.469472,0.642788,0.75471 ,0.829038,0.87462 ,0.927184,
 1.      };            
		double ang_probabilities_40[9] = {0.        ,0.11262215,0.11135544,0.11290005,0.11803754,0.12349247,
 0.12889108,0.13808812,0.15461315};            
		openmc::Tabular ang_dist_40(cos_angles_40, ang_probabilities_40, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_40);

		// Angular distribution for energies 161000.0 < E <= 165000.0            
		double cos_angles_41[8] = {0.438371,0.45399 ,0.5     ,0.656059,0.743145,0.87462 ,0.927184,1.      };            
		double ang_probabilities_41[8] = {0.        ,0.13027052,0.1282012 ,0.12999378,0.13401748,0.14637538,
 0.15616642,0.1749752 };            
		openmc::Tabular ang_dist_41(cos_angles_41, ang_probabilities_41, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_41);

		// Angular distribution for energies 165000.0 < E <= 169000.0            
		double cos_angles_42[8] = {0.469472,0.48481 ,0.515038,0.681998,0.75471 ,0.882948,0.93358 ,1.      };            
		double ang_probabilities_42[8] = {0.        ,0.13017177,0.12890923,0.13095648,0.13459868,0.14667666,
 0.15582399,0.17286318};            
		openmc::Tabular ang_dist_42(cos_angles_42, ang_probabilities_42, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_42);

		// Angular distribution for energies 169000.0 < E <= 173000.0            
		double cos_angles_43[8] = {0.48481 ,0.5     ,0.544639,0.707107,0.75471 ,0.891007,0.939693,1.      };            
		double ang_probabilities_43[8] = {0.        ,0.13142082,0.12963937,0.13188732,0.13425405,0.14690435,
 0.15536097,0.17053312};            
		openmc::Tabular ang_dist_43(cos_angles_43, ang_probabilities_43, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_43);

		// Angular distribution for energies 173000.0 < E <= 177000.0            
		double cos_angles_44[7] = {0.515038,0.529919,0.707107,0.766044,0.906308,0.951057,1.      };            
		double ang_probabilities_44[7] = {0.        ,0.15073415,0.15201652,0.15470861,0.17016548,0.17921998,
 0.19315527};            
		openmc::Tabular ang_dist_44(cos_angles_44, ang_probabilities_44, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_44);

		// Angular distribution for energies 177000.0 < E <= 181000.0            
		double cos_angles_45[6] = {0.529919,0.544639,0.587785,0.777146,0.913545,1.      };            
		double ang_probabilities_45[6] = {0.        ,0.18578242,0.18376447,0.18960565,0.20811368,0.23273378};            
		openmc::Tabular ang_dist_45(cos_angles_45, ang_probabilities_45, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_45);

		// Angular distribution for energies 181000.0 < E <= 185000.0            
		double cos_angles_46[6] = {0.544639,0.559193,0.601815,0.788011,0.920505,1.      };            
		double ang_probabilities_46[6] = {0.        ,0.18747503,0.18446799,0.19015531,0.20829525,0.22960643};            
		openmc::Tabular ang_dist_46(cos_angles_46, ang_probabilities_46, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_46);

		// Angular distribution for energies 185000.0 < E <= 189000.0            
		double cos_angles_47[6] = {0.573576,0.587785,0.615661,0.798636,0.920505,1.      };            
		double ang_probabilities_47[6] = {0.        ,0.18759598,0.18581341,0.19128278,0.20791804,0.2273898 };            
		openmc::Tabular ang_dist_47(cos_angles_47, ang_probabilities_47, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_47);

		// Angular distribution for energies 189000.0 < E <= 193000.0            
		double cos_angles_48[6] = {0.587785,0.601815,0.642788,0.809017,0.920505,1.      };            
		double ang_probabilities_48[6] = {0.        ,0.18930394,0.18682203,0.19194504,0.207051  ,0.22487799};            
		openmc::Tabular ang_dist_48(cos_angles_48, ang_probabilities_48, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_48);

		// Angular distribution for energies 193000.0 < E <= 197000.0            
		double cos_angles_49[6] = {0.601815,0.615661,0.656059,0.819152,0.906308,1.      };            
		double ang_probabilities_49[6] = {0.        ,0.19152428,0.18805168,0.19304803,0.20418728,0.22318872};            
		openmc::Tabular ang_dist_49(cos_angles_49, ang_probabilities_49, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_49);

		// Angular distribution for energies 197000.0 < E <= 201000.0            
		double cos_angles_50[6] = {0.62932 ,0.642788,0.681998,0.838671,0.913545,1.      };            
		double ang_probabilities_50[6] = {0.        ,0.19101959,0.18902536,0.19436204,0.20428015,0.22131287};            
		openmc::Tabular ang_dist_50(cos_angles_50, ang_probabilities_50, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_50);

		// Angular distribution for energies 201000.0 < E <= 205000.0            
		double cos_angles_51[6] = {0.642788,0.656059,0.694658,0.848048,0.913545,1.      };            
		double ang_probabilities_51[6] = {0.        ,0.19265525,0.1896827 ,0.19488938,0.20308439,0.21968827};            
		openmc::Tabular ang_dist_51(cos_angles_51, ang_probabilities_51, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_51);

		// Angular distribution for energies 205000.0 < E <= 209000.0            
		double cos_angles_52[6] = {0.669131,0.681998,0.71934 ,0.866025,0.920505,1.      };            
		double ang_probabilities_52[6] = {0.        ,0.19219424,0.19059922,0.19602943,0.20296708,0.21821004};            
		openmc::Tabular ang_dist_52(cos_angles_52, ang_probabilities_52, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_52);

		// Angular distribution for energies 209000.0 < E <= 213000.0            
		double cos_angles_53[6] = {0.681998,0.694658,0.731354,0.87462 ,0.927184,1.      };            
		double ang_probabilities_53[6] = {0.        ,0.19356674,0.19099714,0.19631051,0.20257419,0.21655141};            
		openmc::Tabular ang_dist_53(cos_angles_53, ang_probabilities_53, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_53);

		// Angular distribution for energies 213000.0 < E <= 217000.0            
		double cos_angles_54[5] = {0.694658,0.707107,0.743145,0.891007,1.      };            
		double ang_probabilities_54[5] = {0.        ,0.244284  ,0.23980792,0.24687618,0.26903189};            
		openmc::Tabular ang_dist_54(cos_angles_54, ang_probabilities_54, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_54);

		// Angular distribution for energies 217000.0 < E <= 221000.0            
		double cos_angles_55[5] = {0.71934 ,0.731354,0.766044,0.906308,1.      };            
		double ang_probabilities_55[5] = {0.        ,0.24378063,0.24087936,0.24818502,0.26715499};            
		openmc::Tabular ang_dist_55(cos_angles_55, ang_probabilities_55, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_55);

		// Angular distribution for energies 221000.0 < E <= 225000.0            
		double cos_angles_56[5] = {0.731354,0.743145,0.777146,0.913545,1.      };            
		double ang_probabilities_56[5] = {0.        ,0.24556123,0.24137055,0.24835235,0.26471587};            
		openmc::Tabular ang_dist_56(cos_angles_56, ang_probabilities_56, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_56);

		// Angular distribution for energies 225000.0 < E <= 229000.0            
		double cos_angles_57[5] = {0.75471 ,0.766044,0.798636,0.927184,1.      };            
		double ang_probabilities_57[5] = {0.        ,0.24525297,0.24243806,0.24954808,0.2627609 };            
		openmc::Tabular ang_dist_57(cos_angles_57, ang_probabilities_57, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_57);

		// Angular distribution for energies 229000.0 < E <= 233000.0            
		double cos_angles_58[5] = {0.766044,0.777146,0.829038,0.945519,1.      };            
		double ang_probabilities_58[5] = {0.        ,0.24666957,0.24324186,0.25023199,0.25985658};            
		openmc::Tabular ang_dist_58(cos_angles_58, ang_probabilities_58, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_58);

		// Angular distribution for energies 233000.0 < E <= 237000.0            
		double cos_angles_59[5] = {0.788011,0.798636,0.838671,0.956305,1.      };            
		double ang_probabilities_59[5] = {0.        ,0.24661802,0.24394393,0.25128045,0.2581576 };            
		openmc::Tabular ang_dist_59(cos_angles_59, ang_probabilities_59, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_59);

		// Angular distribution for energies 237000.0 < E <= 241000.0            
		double cos_angles_60[4] = {0.798636,0.809017,0.848048,1.      };            
		double ang_probabilities_60[4] = {0.        ,0.33189722,0.3260621 ,0.34204069};            
		openmc::Tabular ang_dist_60(cos_angles_60, ang_probabilities_60, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_60);

		// Angular distribution for energies 241000.0 < E <= 245000.0            
		double cos_angles_61[4] = {0.819152,0.829038,0.866025,1.      };            
		double ang_probabilities_61[4] = {0.        ,0.33189016,0.32743719,0.34067265};            
		openmc::Tabular ang_dist_61(cos_angles_61, ang_probabilities_61, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_61);

		// Angular distribution for energies 245000.0 < E <= 249000.0            
		double cos_angles_62[4] = {0.829038,0.838671,0.87462 ,1.      };            
		double ang_probabilities_62[4] = {0.        ,0.33406701,0.32724237,0.33869062};            
		openmc::Tabular ang_dist_62(cos_angles_62, ang_probabilities_62, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_62);

		// Angular distribution for energies 249000.0 < E <= 253000.0            
		double cos_angles_63[4] = {0.848048,0.857167,0.891007,1.      };            
		double ang_probabilities_63[4] = {0.        ,0.33387459,0.32804878,0.33807663};            
		openmc::Tabular ang_dist_63(cos_angles_63, ang_probabilities_63, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_63);

		// Angular distribution for energies 253000.0 < E <= 257000.0            
		double cos_angles_64[4] = {0.866025,0.87462 ,0.906308,1.      };            
		double ang_probabilities_64[4] = {0.        ,0.33381805,0.32866163,0.33752032};            
		openmc::Tabular ang_dist_64(cos_angles_64, ang_probabilities_64, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_64);

		// Angular distribution for energies 257000.0 < E <= 261000.0            
		double cos_angles_65[4] = {0.87462 ,0.882948,0.920505,1.      };            
		double ang_probabilities_65[4] = {0.        ,0.33599949,0.32816659,0.33583392};            
		openmc::Tabular ang_dist_65(cos_angles_65, ang_probabilities_65, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_65);

		// Angular distribution for energies 261000.0 < E <= 265000.0            
		double cos_angles_66[4] = {0.891007,0.898794,0.93358 ,1.      };            
		double ang_probabilities_66[4] = {0.        ,0.33627594,0.3286884 ,0.33503566};            
		openmc::Tabular ang_dist_66(cos_angles_66, ang_probabilities_66, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_66);

		// Angular distribution for energies 265000.0 < E <= 269000.0            
		double cos_angles_67[4] = {0.906308,0.913545,0.945519,1.      };            
		double ang_probabilities_67[4] = {0.        ,0.33683559,0.32918458,0.33397983};            
		openmc::Tabular ang_dist_67(cos_angles_67, ang_probabilities_67, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_67);

		// Angular distribution for energies 269000.0 < E <= 273000.0            
		double cos_angles_68[4] = {0.920505,0.927184,0.956305,1.      };            
		double ang_probabilities_68[4] = {0.        ,0.33767634,0.32971381,0.33260985};            
		openmc::Tabular ang_dist_68(cos_angles_68, ang_probabilities_68, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_68);

		// Angular distribution for energies 273000.0 < E <= 277000.0            
		double cos_angles_69[4] = {0.939693,0.945519,0.970296,1.      };            
		double ang_probabilities_69[4] = {0.        ,0.33725701,0.33083712,0.33190588};            
		openmc::Tabular ang_dist_69(cos_angles_69, ang_probabilities_69, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_69);

		// Angular distribution for energies 277000.0 < E <= 281000.0            
		double cos_angles_70[3] = {0.951057,0.956305,1.      };            
		double ang_probabilities_70[3] = {0.       ,0.5061946,0.4938054};            
		openmc::Tabular ang_dist_70(cos_angles_70, ang_probabilities_70, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_70);

		// Angular distribution for energies 281000.0 < E <= 285000.0            
		double cos_angles_71[3] = {0.965926,0.970296,1.      };            
		double ang_probabilities_71[3] = {0.       ,0.5062685,0.4937315};            
		openmc::Tabular ang_dist_71(cos_angles_71, ang_probabilities_71, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_71);

		// Angular distribution for energies 285000.0 < E <= 289000.0            
		double cos_angles_72[3] = {0.981627,0.984808,1.      };            
		double ang_probabilities_72[3] = {0.        ,0.50433941,0.49566059};            
		openmc::Tabular ang_dist_72(cos_angles_72, ang_probabilities_72, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_72);

		// Angular distribution for energies 289000.0 < E <= 292000.0            
		double cos_angles_73[3] = {0.992546,0.994522,1.      };            
		double ang_probabilities_73[3] = {0.        ,0.50184193,0.49815807};            
		openmc::Tabular ang_dist_73(cos_angles_73, ang_probabilities_73, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_73);

		// Choose angular distribution depending on sampled energy    
		for (int n = 0; n < 73; n++) {    
			if (energy < edges[n]) {     
				mu = ang_dists[n].sample(seed);    
				break;
			}
		}

		// Convert sampled mu to angle    
		theta = std::acos(mu);    
		// Sample phi in range [0,2pi];    
		phi = 2.0 * M_PI * openmc::prn(seed);    

		// Set directional vector    
		particle.u = {std::sin(theta)*std::cos(phi), std::sin(theta)*std::sin(phi), mu};

		// Sample particle starting position
		openmc::PowerLaw r_dist(0, 5, 1);    
		pos_r = r_dist.sample(seed);    
		pos_ang = 2.0 * M_PI * openmc::prn(seed);    
		// Set position of particle    
		particle.r = {pos_r*std::cos(pos_ang), pos_r*std::sin(pos_ang) - 42, 0.0};

		// Return particle    
		return particle;    
	}    
};

// Function to create unique pointer to an instance of this class when generated via a plugin call using dlopen/dlsym    
extern "C" std::unique_ptr<Li_source> openmc_create_source(std::string parameters) {    
	return std::make_unique<Li_source>();    
}