/*
Source file for OpenMC generated by MCNP_to_OpenMC.py script by Max Conroy.    

Distributions based on MCNP SDEF file by Daniel Minsky.    

Details:
	Generated on 13-02-2024.    

For more information, please contact m.j.conroy@pgr.bham.ac.uk.
*/
#include <memory>
#include <cmath>
#include <vector>
#include <iostream>
#include "openmc/random_lcg.h"
#include "openmc/source.h"
#include "openmc/particle.h"
#include "openmc/distribution.h"

// Create new source class which inherits from openmc::Source    
class Li_source : public openmc::Source {

	// Define a function called "sample" to generate neutrons
	openmc::SourceSite sample(uint64_t* seed) const {

		openmc::SourceSite particle;
		// Define particle type
		particle.particle = openmc::ParticleType::neutron;    
		// Define particle weight
		particle.wgt = 2.182764e+11;

		// Initialise required variables    
		double energy {0.0};
		double mu {0.0};    
		double theta {0.0};
		double phi {0.0};    
		double pos_r {0.0};
		double pos_ang {0.0};

		// Define energies and probabilities for distribution    
		double energies[154] = {     0.,  1000.,  2000.,  3000.,  5000.,  7000.,  9000., 15000., 24000.,
  35000., 52000., 89000.,106000.,108000.,126000.,128000.,135000.,137000.,
 140000.,142000.,145000.,147000.,150000.,152000.,155000.,160000.,163000.,
 168000.,169000.,171000.,172000.,174000.,175000.,177000.,178000.,180000.,
 183000.,185000.,186000.,188000.,189000.,192000.,193000.,195000.,196000.,
 198000.,199000.,201000.,202000.,204000.,205000.,207000.,208000.,210000.,
 211000.,213000.,214000.,217000.,218000.,220000.,221000.,223000.,224000.,
 226000.,227000.,229000.,230000.,233000.,234000.,236000.,237000.,239000.,
 240000.,242000.,243000.,246000.,247000.,249000.,250000.,252000.,253000.,
 255000.,256000.,258000.,259000.,261000.,262000.,265000.,266000.,268000.,
 269000.,271000.,272000.,274000.,275000.,277000.,278000.,280000.,281000.,
 283000.,284000.,286000.,287000.,289000.,290000.,291000.,292000.,294000.,
 295000.,297000.,298000.,300000.,301000.,302000.,303000.,305000.,306000.,
 308000.,309000.,310000.,311000.,313000.,314000.,315000.,316000.,317000.,
 318000.,319000.,320000.,322000.,323000.,324000.,325000.,326000.,327000.,
 328000.,329000.,330000.,331000.,332000.,334000.,335000.,337000.,338000.,
 340000.,341000.,343000.,344000.,346000.,347000.,348000.,349000.,350000.,
 351000.};    
		double E_probabilities[154] = {0.00000000e+00,4.77376800e-03,6.76932414e-03,8.29927972e-03,
 1.07105114e-02,1.26482443e-02,1.43006570e-02,1.82925197e-02,
 2.26008549e-02,2.59578368e-02,2.89820388e-02,2.30042348e-02,
 2.06647748e-02,2.01233486e-02,1.75833942e-02,1.75814979e-02,
 1.63559346e-02,1.63391180e-02,1.57161655e-02,1.56965844e-02,
 1.50702007e-02,1.50491584e-02,1.44215652e-02,1.43992394e-02,
 1.37717300e-02,1.34170534e-02,1.27927816e-02,1.24402747e-02,
 1.21373435e-02,1.21137364e-02,1.18124679e-02,1.17893537e-02,
 1.14899555e-02,1.14674242e-02,1.11700800e-02,1.11481914e-02,
 1.05496345e-02,1.05287439e-02,1.02385335e-02,1.02183236e-02,
 9.93077192e-03,9.90170756e-03,9.61692039e-03,9.59832328e-03,
 9.31642638e-03,9.29839015e-03,9.01948731e-03,9.00196805e-03,
 8.72617305e-03,8.70915480e-03,8.43659139e-03,8.42009011e-03,
 8.15090001e-03,8.13495962e-03,7.86928455e-03,7.85397691e-03,
 7.59197455e-03,7.57036940e-03,7.31221341e-03,7.29881398e-03,
 7.04463411e-03,7.03212292e-03,6.78205090e-03,6.77048584e-03,
 6.52464343e-03,6.51407239e-03,6.27257337e-03,6.25859908e-03,
 6.02159314e-03,6.01353313e-03,5.78103625e-03,5.77397026e-03,
 5.54603434e-03,5.53990250e-03,5.31656146e-03,5.30893459e-03,
 5.09022636e-03,5.08610853e-03,4.87204708e-03,4.86867777e-03,
 4.65931700e-03,4.65670019e-03,4.45209399e-03,4.45026163e-03,
 4.25047986e-03,4.24948583e-03,4.05459038e-03,4.05476603e-03,
 3.86485069e-03,3.86615012e-03,3.68124285e-03,3.68355626e-03,
 3.50370098e-03,3.50707429e-03,3.33230691e-03,3.33674610e-03,
 3.16705666e-03,3.17248589e-03,3.00781848e-03,3.01407008e-03,
 2.85432291e-03,2.86115337e-03,2.70618272e-03,2.71327665e-03,
 2.56290888e-03,2.56641992e-03,2.42069295e-03,2.42750344e-03,
 2.28618572e-03,2.29274671e-03,2.15580032e-03,2.16213975e-03,
 2.02957866e-03,2.03266254e-03,1.90465263e-03,1.91070682e-03,
 1.78709758e-03,1.79314938e-03,1.67392404e-03,1.67692270e-03,
 1.56217228e-03,1.56810372e-03,1.45764719e-03,1.46057020e-03,
 1.35448919e-03,1.35733415e-03,1.25557896e-03,1.25834368e-03,
 1.16086501e-03,1.16628746e-03,1.07290287e-03,1.07555980e-03,
 9.86352130e-04,9.88924828e-04,9.03837784e-04,9.06319462e-04,
 8.25293763e-04,8.27674042e-04,7.50646813e-04,7.52912320e-04,
 6.10736503e-04,6.12712783e-04,4.86031435e-04,4.87659406e-04,
 3.75936391e-04,3.77153776e-04,2.79966931e-04,2.36872003e-04,
 1.61557916e-04,1.29305024e-04,1.00637202e-04,5.38783211e-05,
 1.07712590e-05,0.00000000e+00};
		// Define energy distribution
		openmc::Tabular E_dist(energies, E_probabilities, 154, openmc::Interpolation::lin_lin);
		// Sample energy from distribution
		energy = E_dist.sample(seed);
		particle.E = energy;

		// Define energy values for bin edges to choose angular distribution    
		double edges[88] = {  5000.,  9000., 13000., 17000., 21000., 25000., 29000., 33000., 37000.,
  41000., 45000., 49000., 53000., 57000., 61000., 65000., 69000., 73000.,
  77000., 81000., 85000., 89000., 93000., 97000.,101000.,105000.,109000.,
 113000.,117000.,121000.,125000.,129000.,133000.,137000.,141000.,145000.,
 149000.,153000.,157000.,161000.,165000.,169000.,173000.,177000.,181000.,
 185000.,189000.,193000.,197000.,201000.,205000.,209000.,213000.,217000.,
 221000.,225000.,229000.,233000.,237000.,241000.,245000.,249000.,253000.,
 257000.,261000.,265000.,269000.,273000.,277000.,281000.,285000.,289000.,
 293000.,297000.,301000.,305000.,309000.,313000.,317000.,321000.,325000.,
 329000.,333000.,337000.,341000.,345000.,349000.,351000.};

		// Create vector to hold angular distributions        
		std::vector<openmc::Tabular> ang_dists;

		// Angular distribution for energies 0.0 < E <= 5000.0            
		double cos_angles_1[6] = {-1.       ,-0.052336 ,-0.0348995, 0.515038 , 0.766044 , 1.       };            
		double ang_probabilities_1[6] = {0.13454542,0.15214883,0.1478466 ,0.17108408,0.1870698 ,0.20730527};            
		openmc::Tabular ang_dist_1(cos_angles_1, ang_probabilities_1, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_1);

		// Angular distribution for energies 5000.0 < E <= 9000.0            
		double cos_angles_2[9] = {-1.      ,-0.358368, 0.104528, 0.121869, 0.374607, 0.601815, 0.809017,
  0.906308, 1.      };            
		double ang_probabilities_2[9] = {0.07824939,0.08623586,0.09513689,0.09266001,0.10218601,0.11458028,
 0.13148015,0.14265184,0.15681957};            
		openmc::Tabular ang_dist_2(cos_angles_2, ang_probabilities_2, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_2);

		// Angular distribution for energies 9000.0 < E <= 13000.0            
		double cos_angles_3[11] = {-1.      ,-0.601815,-0.139173, 0.190809, 0.207912, 0.438371, 0.656059,
  0.75471 , 0.838671, 0.927184, 1.      };            
		double ang_probabilities_3[11] = {0.06040601,0.06180932,0.06806523,0.07454513,0.07268065,0.08155196,
 0.09461814,0.10320713,0.11278949,0.12669271,0.14363425};            
		openmc::Tabular ang_dist_3(cos_angles_3, ang_probabilities_3, 11, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_3);

		// Angular distribution for energies 13000.0 < E <= 17000.0            
		double cos_angles_4[14] = {-1.      ,-0.642788,-0.469472,-0.052336, 0.258819, 0.275637, 0.5     ,
  0.601815, 0.694658, 0.788011, 0.866025, 0.939693, 0.970296, 1.      };            
		double ang_probabilities_4[14] = {0.04428786,0.04432437,0.04502328,0.04972589,0.05496835,0.05367896,
 0.06147388,0.06655697,0.07256619,0.08067927,0.0901531 ,0.10345174,
 0.11137646,0.12173368};            
		openmc::Tabular ang_dist_4(cos_angles_4, ang_probabilities_4, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_4);

		// Angular distribution for energies 17000.0 < E <= 21000.0            
		double cos_angles_5[14] = {-1.       ,-0.374607 , 0.0174524, 0.309017 , 0.325568 , 0.529919 ,
  0.62932  , 0.71934  , 0.809017 , 0.882948 , 0.920505 , 0.951057 ,
  0.978148 , 1.       };            
		double ang_probabilities_5[14] = {0.03990272,0.04011931,0.04444427,0.04943686,0.04827009,0.05552168,
 0.06067785,0.06690758,0.07557226,0.08613356,0.09375038,0.10204363,
 0.11231831,0.12490148};            
		openmc::Tabular ang_dist_5(cos_angles_5, ang_probabilities_5, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_5);

		// Angular distribution for energies 21000.0 < E <= 25000.0            
		double cos_angles_6[17] = {-1.       ,-0.731354 ,-0.292372 ,-0.0348995, 0.156434 , 0.358368 ,
  0.374607 , 0.573576 , 0.669131 , 0.75471  , 0.838671 , 0.906308 ,
  0.93358  , 0.961262 , 0.984808 , 0.992546 , 1.       };            
		double ang_probabilities_6[17] = {0.03169453,0.03093019,0.03124084,0.03337422,0.03565515,0.03883935,
 0.03797669,0.04429153,0.04885833,0.05446193,0.06243058,0.07247867,
 0.078426  ,0.0867924 ,0.09794333,0.10350369,0.11110257};            
		openmc::Tabular ang_dist_6(cos_angles_6, ang_probabilities_6, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_6);

		// Angular distribution for energies 25000.0 < E <= 29000.0            
		double cos_angles_7[20] = {-1.       ,-0.601815 ,-0.207912 , 0.0348995, 0.207912 , 0.390731 ,
  0.406737 , 0.5      , 0.601815 , 0.694658 , 0.777146 , 0.857167 ,
  0.891007 , 0.920505 , 0.945519 , 0.970296 , 0.981627 , 0.990268 ,
  0.996195 , 1.       };            
		double ang_probabilities_7[20] = {0.02494149,0.02436464,0.02463899,0.02637101,0.02816218,0.03069123,
 0.02993536,0.03212048,0.03525665,0.0391538 ,0.04398856,0.05097295,
 0.05519317,0.0600044 ,0.0655054 ,0.07352605,0.07903507,0.0850939 ,
 0.09158228,0.09946239};            
		openmc::Tabular ang_dist_7(cos_angles_7, ang_probabilities_7, 20, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_7);

		// Angular distribution for energies 29000.0 < E <= 33000.0            
		double cos_angles_8[22] = {-1.       ,-0.777146 ,-0.5      ,-0.139173 , 0.0871557, 0.258819 ,
  0.438371 , 0.45399  , 0.544639 , 0.62932  , 0.71934  , 0.798636 ,
  0.866025 , 0.898794 , 0.927184 , 0.951057 , 0.97437  , 0.984808 ,
  0.992546 , 0.997564 , 0.999391 , 1.       };            
		double ang_probabilities_8[22] = {0.02156424,0.02172235,0.02117634,0.02142946,0.02291359,0.0246025 ,
 0.0269432 ,0.02637663,0.02844925,0.03096794,0.03458313,0.03909581,
 0.04474885,0.04861829,0.05305473,0.05816316,0.06569414,0.07094269,
 0.07682636,0.08336945,0.0879134 ,0.09084448};            
		openmc::Tabular ang_dist_8(cos_angles_8, ang_probabilities_8, 22, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_8);

		// Angular distribution for energies 33000.0 < E <= 37000.0            
		double cos_angles_9[21] = {-1.       ,-0.857167 ,-0.669131 ,-0.406737 ,-0.0871557, 0.121869 ,
  0.309017 , 0.469472 , 0.48481  , 0.573576 , 0.656059 , 0.731354 ,
  0.798636 , 0.866025 , 0.898794 , 0.927184 , 0.951057 , 0.970296 ,
  0.987688 , 0.994522 , 1.       };            
		double ang_probabilities_9[21] = {0.02676983,0.02571272,0.02597223,0.02534233,0.02563936,0.02727756,
 0.02966362,0.03240188,0.03168706,0.03429142,0.03746407,0.04131152,
 0.04597011,0.05266951,0.05724195,0.06245996,0.06841719,0.07519719,
 0.08481678,0.0909088 ,0.09878491};            
		openmc::Tabular ang_dist_9(cos_angles_9, ang_probabilities_9, 21, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_9);

		// Angular distribution for energies 37000.0 < E <= 41000.0            
		double cos_angles_10[19] = {-1.      ,-0.75471 ,-0.573576,-0.325568,-0.052336, 0.121869, 0.325568,
  0.5     , 0.515038, 0.669131, 0.743145, 0.809017, 0.866025, 0.920505,
  0.945519, 0.965926, 0.984808, 0.992546, 1.      };            
		double ang_probabilities_10[19] = {0.03113435,0.02930209,0.02959882,0.02891027,0.0292154 ,0.0305467 ,
 0.03358087,0.03716709,0.03632585,0.04252872,0.04696842,0.05233418,
 0.05880853,0.0680483 ,0.07425914,0.08116456,0.09051954,0.09606135,
 0.10352584};            
		openmc::Tabular ang_dist_10(cos_angles_10, ang_probabilities_10, 19, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_10);

		// Angular distribution for energies 41000.0 < E <= 45000.0            
		double cos_angles_11[19] = {-1.       ,-0.829038 ,-0.681998 ,-0.5      ,-0.275637 , 0.0174524,
  0.190809 , 0.374607 , 0.529919 , 0.544639 , 0.656059 , 0.766044 ,
  0.809017 , 0.857167 , 0.898794 , 0.939693 , 0.97437  , 0.987688 ,
  1.       };            
		double ang_probabilities_11[19] = {0.03451156,0.03373499,0.03216283,0.03244559,0.03171162,0.03214908,
 0.03391346,0.03721323,0.0410143 ,0.04007892,0.04496301,0.05219131,
 0.05610939,0.06171787,0.06820384,0.07722879,0.08922592,0.09617335,
 0.10525093};            
		openmc::Tabular ang_dist_11(cos_angles_11, ang_probabilities_11, 19, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_11);

		// Angular distribution for energies 45000.0 < E <= 49000.0            
		double cos_angles_12[17] = {-1.       ,-0.75471  ,-0.601815 ,-0.422618 ,-0.224951 , 0.0697565,
  0.207912 , 0.406737 , 0.559193 , 0.573576 , 0.656059 , 0.766044 ,
  0.857167 , 0.898794 , 0.939693 , 0.97437  , 1.       };            
		double ang_probabilities_12[17] = {0.04201265,0.04075247,0.03874481,0.03907951,0.03824027,0.03884066,
 0.04051368,0.04499562,0.04977784,0.04865046,0.05307031,0.06150179,
 0.07251724,0.07991417,0.09000499,0.10288577,0.11849776};            
		openmc::Tabular ang_dist_12(cos_angles_12, ang_probabilities_12, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_12);

		// Angular distribution for energies 49000.0 < E <= 53000.0            
		double cos_angles_13[17] = {-1.      ,-0.669131,-0.515038,-0.358368,-0.104528, 0.104528, 0.207912,
  0.422618, 0.587785, 0.601815, 0.656059, 0.75471 , 0.848048, 0.891007,
  0.93358 , 0.970296, 1.      };            
		double ang_probabilities_13[17] = {0.04394557,0.04184303,0.03976015,0.04017836,0.03938628,0.03997059,
 0.04106446,0.04604156,0.05158309,0.05043658,0.05346249,0.06078362,
 0.07132165,0.07832592,0.08775873,0.09957157,0.11456635};            
		openmc::Tabular ang_dist_13(cos_angles_13, ang_probabilities_13, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_13);

		// Angular distribution for energies 53000.0 < E <= 57000.0            
		double cos_angles_14[18] = {-0.939693 ,-0.93358  ,-0.615661 ,-0.438371 ,-0.292372 ,-0.0697565,
  0.139173 , 0.241922 , 0.45399  , 0.615661 , 0.62932  , 0.656059 ,
  0.75471  , 0.848048 , 0.891007 , 0.93358  , 0.970296 , 1.       };            
		double ang_probabilities_14[18] = {0.        ,0.04478552,0.04278934,0.04046994,0.04091326,0.04012416,
 0.04076704,0.04186588,0.04713131,0.05297865,0.05183415,0.05337008,
 0.06055395,0.07080942,0.07753998,0.08645489,0.09729616,0.11031628};            
		openmc::Tabular ang_dist_14(cos_angles_14, ang_probabilities_14, 18, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_14);

		// Angular distribution for energies 57000.0 < E <= 61000.0            
		double cos_angles_15[18] = {-0.866025 ,-0.857167 ,-0.544639 ,-0.390731 ,-0.241922 ,-0.0174524,
  0.190809 , 0.275637 , 0.48481  , 0.642788 , 0.656059 , 0.669131 ,
  0.766044 , 0.848048 , 0.891007 , 0.927184 , 0.965926 , 1.       };            
		double ang_probabilities_15[18] = {0.        ,0.04565402,0.04353619,0.04123491,0.04166505,0.0409033 ,
 0.0416832 ,0.04270317,0.04826819,0.05441631,0.05328241,0.05407273,
 0.06131875,0.07028838,0.07675185,0.08374406,0.09379991,0.10667756};            
		openmc::Tabular ang_dist_15(cos_angles_15, ang_probabilities_15, 18, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_15);

		// Angular distribution for energies 61000.0 < E <= 65000.0            
		double cos_angles_16[16] = {-0.788011 ,-0.777146 ,-0.48481  ,-0.325568 ,-0.190809 , 0.0174524,
  0.292372 , 0.374607 , 0.5      , 0.669131 , 0.681998 , 0.777146 ,
  0.857167 , 0.93358  , 0.970296 , 1.       };            
		double ang_probabilities_16[16] = {0.        ,0.05297425,0.05046314,0.04773014,0.04826808,0.04740622,
 0.04926006,0.05129704,0.05571671,0.06361225,0.06234059,0.07063647,
 0.08077452,0.09557033,0.10611614,0.11783406};            
		openmc::Tabular ang_dist_16(cos_angles_16, ang_probabilities_16, 16, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_16);

		// Angular distribution for energies 65000.0 < E <= 69000.0            
		double cos_angles_17[15] = {-0.731354,-0.71934 ,-0.422618,-0.275637,-0.139173, 0.052336, 0.325568,
  0.5     , 0.694658, 0.707107, 0.788011, 0.866025, 0.939693, 0.970296,
  1.      };            
		double ang_probabilities_17[15] = {0.        ,0.05654103,0.05375849,0.05089736,0.05146404,0.05057751,
 0.05267624,0.05856879,0.06846196,0.06715263,0.07488726,0.08540163,
 0.10031063,0.10908776,0.12021468};            
		openmc::Tabular ang_dist_17(cos_angles_17, ang_probabilities_17, 15, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_17);

		// Angular distribution for energies 69000.0 < E <= 73000.0            
		double cos_angles_18[16] = {-0.669131 ,-0.656059 ,-0.374607 ,-0.224951 ,-0.104528 , 0.0871557,
  0.34202  , 0.5      , 0.601815 , 0.71934  , 0.731354 , 0.809017 ,
  0.87462  , 0.939693 , 0.970296 , 1.       };            
		double ang_probabilities_18[16] = {0.        ,0.0538665 ,0.05122072,0.0484112 ,0.04896533,0.04814858,
 0.04996903,0.05486339,0.05923428,0.06574946,0.06454596,0.07196305,
 0.08053087,0.09254981,0.10022825,0.10975357};            
		openmc::Tabular ang_dist_18(cos_angles_18, ang_probabilities_18, 16, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_18);

		// Angular distribution for energies 73000.0 < E <= 77000.0            
		double cos_angles_19[15] = {-0.601815,-0.587785,-0.309017,-0.173648,-0.052336, 0.139173, 0.374607,
  0.529919, 0.62932 , 0.743145, 0.75471 , 0.819152, 0.882948, 0.945519,
  1.      };            
		double ang_probabilities_19[15] = {0.        ,0.06025855,0.05699407,0.05405087,0.05468646,0.05387554,
 0.05601267,0.06170286,0.06673616,0.0741398 ,0.07283513,0.07987692,
 0.08912586,0.10175097,0.11795413};            
		openmc::Tabular ang_dist_19(cos_angles_19, ang_probabilities_19, 15, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_19);

		// Angular distribution for energies 77000.0 < E <= 81000.0            
		double cos_angles_20[15] = {-0.559193 ,-0.544639 ,-0.275637 ,-0.139173 ,-0.0174524, 0.173648 ,
  0.406737 , 0.559193 , 0.656059 , 0.766044 , 0.777146 , 0.838671 ,
  0.891007 , 0.945519 , 1.       };            
		double ang_probabilities_20[15] = {0.        ,0.06057807,0.05745508,0.05430693,0.05491119,0.05414323,
 0.05647083,0.0624206 ,0.06761835,0.07515629,0.07387374,0.08092601,
 0.08865117,0.09925747,0.11423103};            
		openmc::Tabular ang_dist_20(cos_angles_20, ang_probabilities_20, 15, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_20);

		// Angular distribution for energies 81000.0 < E <= 85000.0            
		double cos_angles_21[15] = {-0.5      ,-0.48481  ,-0.224951 ,-0.0871557, 0.0348995, 0.190809 ,
  0.422618 , 0.544639 , 0.669131 , 0.788011 , 0.798636 , 0.857167 ,
  0.906308 , 0.956305 , 1.       };            
		double ang_probabilities_21[15] = {0.        ,0.06090123,0.05759521,0.05445951,0.05510629,0.05432859,
 0.05657997,0.06093536,0.06768313,0.07615284,0.07487633,0.08188934,
 0.08939507,0.09927923,0.1108179 };            
		openmc::Tabular ang_dist_21(cos_angles_21, ang_probabilities_21, 15, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_21);

		// Angular distribution for energies 85000.0 < E <= 89000.0            
		double cos_angles_22[14] = {-0.45399  ,-0.438371 ,-0.173648 ,-0.052336 , 0.0697565, 0.224951 ,
  0.438371 , 0.573576 , 0.694658 , 0.798636 , 0.809017 , 0.906308 ,
  0.956305 , 1.       };            
		double ang_probabilities_22[14] = {0.        ,0.06698924,0.063109  ,0.05982499,0.06053037,0.05972824,
 0.06207367,0.0674454 ,0.07503518,0.08367341,0.08180437,0.09584453,
 0.10608205,0.11785955};            
		openmc::Tabular ang_dist_22(cos_angles_22, ang_probabilities_22, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_22);

		// Angular distribution for energies 89000.0 < E <= 93000.0            
		double cos_angles_23[13] = {-0.406737 ,-0.390731 ,-0.139173 ,-0.0174524, 0.104528 , 0.258819 ,
  0.469472 , 0.601815 , 0.71934  , 0.819152 , 0.829038 , 0.920505 ,
  1.       };            
		double ang_probabilities_23[13] = {0.        ,0.0750439 ,0.07074049,0.06693166,0.06770826,0.0668804 ,
 0.06974614,0.07605841,0.0847273 ,0.09444281,0.09232286,0.10753069,
 0.12786707};            
		openmc::Tabular ang_dist_23(cos_angles_23, ang_probabilities_23, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_23);

		// Angular distribution for energies 93000.0 < E <= 97000.0            
		double cos_angles_24[13] = {-0.358368 ,-0.34202  ,-0.104528 , 0.0174524, 0.139173 , 0.292372 ,
  0.48481  , 0.601815 , 0.731354 , 0.848048 , 0.857167 , 0.927184 ,
  1.       };            
		double ang_probabilities_24[13] = {0.        ,0.07531947,0.07101007,0.06709083,0.06786257,0.06711427,
 0.06985562,0.07503237,0.08469944,0.0963115 ,0.0946046 ,0.10661105,
 0.1244882 };            
		openmc::Tabular ang_dist_24(cos_angles_24, ang_probabilities_24, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_24);

		// Angular distribution for energies 97000.0 < E <= 101000.0            
		double cos_angles_25[13] = {-0.325568 ,-0.309017 ,-0.0697565, 0.052336 , 0.173648 , 0.309017 ,
  0.5      , 0.615661 , 0.75471  , 0.866025 , 0.87462  , 0.939693 ,
  1.       };            
		double ang_probabilities_25[13] = {0.        ,0.0755494 ,0.07117066,0.06716705,0.06794497,0.06718486,
 0.0699156 ,0.07485837,0.08559768,0.09720777,0.09537671,0.10679421,
 0.12123273};            
		openmc::Tabular ang_dist_25(cos_angles_25, ang_probabilities_25, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_25);

		// Angular distribution for energies 101000.0 < E <= 105000.0            
		double cos_angles_26[13] = {-0.275637 ,-0.258819 ,-0.0174524, 0.0871557, 0.190809 , 0.34202  ,
  0.529919 , 0.642788 , 0.777146 , 0.882948 , 0.891007 , 0.945519 ,
  1.       };            
		double ang_probabilities_26[13] = {0.        ,0.0757692 ,0.07090309,0.06725773,0.06804877,0.06737854,
 0.07036331,0.07561091,0.0865281 ,0.09809471,0.09608925,0.10570544,
 0.11825096};            
		openmc::Tabular ang_dist_26(cos_angles_26, ang_probabilities_26, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_26);

		// Angular distribution for energies 105000.0 < E <= 109000.0            
		double cos_angles_27[14] = {-0.241922 ,-0.224951 , 0.0174524, 0.121869 , 0.224951 , 0.374607 ,
  0.544639 , 0.601815 , 0.669131 , 0.798636 , 0.898794 , 0.906308 ,
  0.956305 , 1.       };            
		double ang_probabilities_27[14] = {0.        ,0.07082995,0.06614748,0.06272549,0.06349462,0.06295741,
 0.06563437,0.0674334 ,0.07115606,0.08145348,0.09214331,0.09006228,
 0.09840902,0.10755314};            
		openmc::Tabular ang_dist_27(cos_angles_27, ang_probabilities_27, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_27);

		// Angular distribution for energies 109000.0 < E <= 113000.0            
		double cos_angles_28[13] = {-0.207912 ,-0.190809 , 0.0348995, 0.156434 , 0.258819 , 0.390731 ,
  0.544639 , 0.62932  , 0.731354 , 0.819152 , 0.920505 , 0.927184 ,
  1.       };            
		double ang_probabilities_28[13] = {0.        ,0.07829653,0.07341864,0.06917894,0.07006226,0.0694497 ,
 0.07207864,0.07493352,0.08229288,0.09064211,0.10302462,0.10082658,
 0.11579558};            
		openmc::Tabular ang_dist_28(cos_angles_28, ang_probabilities_28, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_28);

		// Angular distribution for energies 113000.0 < E <= 117000.0            
		double cos_angles_29[13] = {-0.173648 ,-0.156434 , 0.0697565, 0.190809 , 0.292372 , 0.422618 ,
  0.529919 , 0.62932  , 0.707107 , 0.829038 , 0.939693 , 0.945519 ,
  1.       };            
		double ang_probabilities_29[13] = {0.        ,0.07886065,0.07375827,0.06952646,0.07043863,0.06992985,
 0.07181324,0.07457063,0.07934856,0.09081472,0.10475229,0.10249479,
 0.11369192};            
		openmc::Tabular ang_dist_29(cos_angles_29, ang_probabilities_29, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_29);

		// Angular distribution for energies 117000.0 < E <= 121000.0            
		double cos_angles_30[12] = {-0.139173,-0.121869, 0.104528, 0.207912, 0.438371, 0.515038, 0.62932 ,
  0.707107, 0.838671, 0.956305, 0.961262, 1.      };            
		double ang_probabilities_30[12] = {0.        ,0.08531842,0.07955737,0.0751622 ,0.07550477,0.07681381,
 0.07989994,0.0844005 ,0.09772898,0.11413766,0.11148047,0.11999587};            
		openmc::Tabular ang_dist_30(cos_angles_30, ang_probabilities_30, 12, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_30);

		// Angular distribution for energies 121000.0 < E <= 125000.0            
		double cos_angles_31[11] = {-0.104528 ,-0.0871557, 0.139173 , 0.241922 , 0.515038 , 0.642788 ,
  0.71934  , 0.848048 , 0.97437  , 0.978148 , 1.       };            
		double ang_probabilities_31[11] = {0.        ,0.09259043,0.08603704,0.08134147,0.08277116,0.08651819,
 0.09115344,0.10547481,0.12502362,0.12195721,0.12713262};            
		openmc::Tabular ang_dist_31(cos_angles_31, ang_probabilities_31, 11, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_31);

		// Angular distribution for energies 125000.0 < E <= 129000.0            
		double cos_angles_32[11] = {-0.0697565,-0.052336 , 0.173648 , 0.258819 , 0.529919 , 0.656059 ,
  0.731354 , 0.87462  , 0.990268 , 0.992546 , 1.       };            
		double ang_probabilities_32[11] = {0.        ,0.09268077,0.08577972,0.08143884,0.08262875,0.08642914,
 0.09082556,0.10725272,0.12606217,0.12257756,0.12432478};            
		openmc::Tabular ang_dist_32(cos_angles_32, ang_probabilities_32, 11, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_32);

		// Angular distribution for energies 129000.0 < E <= 133000.0            
		double cos_angles_33[9] = {-0.0348995,-0.0174524, 0.190809 , 0.292372 , 0.544639 , 0.681998 ,
  0.75471  , 0.891007 , 1.       };            
		double ang_probabilities_33[9] = {0.        ,0.12285908,0.11411174,0.1076098 ,0.10926315,0.11505458,
 0.1211742 ,0.14276216,0.16716528};            
		openmc::Tabular ang_dist_33(cos_angles_33, ang_probabilities_33, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_33);

		// Angular distribution for energies 133000.0 < E <= 137000.0            
		double cos_angles_34[9] = {-1.03634e-13, 1.74524e-02, 2.24951e-01, 3.09017e-01, 5.59193e-01,
  6.94658e-01, 7.66044e-01, 8.91007e-01, 1.00000e+00};            
		double ang_probabilities_34[9] = {0.        ,0.12355131,0.11430554,0.10834187,0.10965192,0.11552503,
 0.12135281,0.14120036,0.16607115};            
		openmc::Tabular ang_dist_34(cos_angles_34, ang_probabilities_34, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_34);

		// Angular distribution for energies 137000.0 < E <= 141000.0            
		double cos_angles_35[10] = {0.0174524,0.0348995,0.241922 ,0.34202  ,0.573576 ,0.707107 ,0.777146 ,
 0.87462  ,0.945519 ,1.       };            
		double ang_probabilities_35[10] = {0.        ,0.1085869 ,0.10053882,0.09464226,0.09592891,0.10111197,
 0.10595054,0.11890216,0.13104688,0.14329156};            
		openmc::Tabular ang_dist_35(cos_angles_35, ang_probabilities_35, 10, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_35);

		// Angular distribution for energies 141000.0 < E <= 145000.0            
		double cos_angles_36[9] = {0.052336 ,0.0697565,0.275637 ,0.358368 ,0.601815 ,0.731354 ,0.798636 ,
 0.882948 ,1.       };            
		double ang_probabilities_36[9] = {0.        ,0.12537559,0.11555436,0.10938952,0.11095859,0.1172497 ,
 0.12304956,0.13625234,0.16217034};            
		openmc::Tabular ang_dist_36(cos_angles_36, ang_probabilities_36, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_36);

		// Angular distribution for energies 145000.0 < E <= 149000.0            
		double cos_angles_37[9] = {0.0697565,0.0871557,0.292372 ,0.390731 ,0.615661 ,0.743145 ,0.809017 ,
 0.882948 ,1.       };            
		double ang_probabilities_37[9] = {0.        ,0.12651094,0.11668025,0.10969712,0.1114645 ,0.11782356,
 0.12334592,0.13457176,0.15990594};            
		openmc::Tabular ang_dist_37(cos_angles_37, ang_probabilities_37, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_37);

		// Angular distribution for energies 149000.0 < E <= 153000.0            
		double cos_angles_38[9] = {0.104528,0.121869,0.325568,0.406737,0.62932 ,0.743145,0.819152,0.891007,
 1.      };            
		double ang_probabilities_38[9] = {0.        ,0.12730661,0.11681863,0.11047893,0.1119332 ,0.11762269,
 0.12360762,0.13435046,0.15788186};            
		openmc::Tabular ang_dist_38(cos_angles_38, ang_probabilities_38, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_38);

		// Angular distribution for energies 153000.0 < E <= 157000.0            
		double cos_angles_39[9] = {0.139173,0.156434,0.34202 ,0.438371,0.642788,0.743145,0.829038,0.898794,
 1.      };            
		double ang_probabilities_39[9] = {0.        ,0.12793855,0.1178213 ,0.11067907,0.11236268,0.1173231 ,
 0.12383285,0.13403818,0.15600427};            
		openmc::Tabular ang_dist_39(cos_angles_39, ang_probabilities_39, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_39);

		// Angular distribution for energies 157000.0 < E <= 161000.0            
		double cos_angles_40[9] = {0.156434,0.173648,0.374607,0.45399 ,0.656059,0.75471 ,0.848048,0.913545,
 1.      };            
		double ang_probabilities_40[9] = {0.        ,0.12866597,0.11747065,0.11102567,0.11246176,0.11734359,
 0.1247037 ,0.13462448,0.15370417};            
		openmc::Tabular ang_dist_40(cos_angles_40, ang_probabilities_40, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_40);

		// Angular distribution for energies 161000.0 < E <= 165000.0            
		double cos_angles_41[8] = {0.190809,0.207912,0.48481 ,0.669131,0.75471 ,0.857167,0.920505,1.      };            
		double ang_probabilities_41[8] = {0.        ,0.14666069,0.12623434,0.12814107,0.13272623,0.14172793,
 0.15228564,0.17222411};            
		openmc::Tabular ang_dist_41(cos_angles_41, ang_probabilities_41, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_41);

		// Angular distribution for energies 165000.0 < E <= 169000.0            
		double cos_angles_42[9] = {0.207912,0.224951,0.422618,0.5     ,0.681998,0.75471 ,0.866025,0.927184,
 1.      };            
		double ang_probabilities_42[9] = {0.        ,0.13050266,0.1184836 ,0.1119681 ,0.11349703,0.11665365,
 0.12520664,0.1338717 ,0.14981663};            
		openmc::Tabular ang_dist_42(cos_angles_42, ang_probabilities_42, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_42);

		// Angular distribution for energies 169000.0 < E <= 173000.0            
		double cos_angles_43[9] = {0.224951,0.241922,0.438371,0.515038,0.707107,0.777146,0.882948,0.939693,
 1.      };            
		double ang_probabilities_43[9] = {0.        ,0.13107299,0.11897262,0.11224089,0.1137287 ,0.117189  ,
 0.12577176,0.13397042,0.14705363};            
		openmc::Tabular ang_dist_43(cos_angles_43, ang_probabilities_43, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_43);

		// Angular distribution for energies 173000.0 < E <= 177000.0            
		double cos_angles_44[8] = {0.258819,0.275637,0.544639,0.71934 ,0.788011,0.891007,0.945519,1.      };            
		double ang_probabilities_44[8] = {0.        ,0.14961723,0.12767644,0.12977121,0.13348582,0.14311797,
 0.15166216,0.16466917};            
		openmc::Tabular ang_dist_44(cos_angles_44, ang_probabilities_44, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_44);

		// Angular distribution for energies 177000.0 < E <= 181000.0            
		double cos_angles_45[9] = {0.275637,0.292372,0.48481 ,0.544639,0.587785,0.743145,0.798636,0.920505,
 1.      };            
		double ang_probabilities_45[9] = {0.        ,0.13507176,0.1218405 ,0.11592884,0.11466963,0.11684858,
 0.11970476,0.13070929,0.14522664};            
		openmc::Tabular ang_dist_45(cos_angles_45, ang_probabilities_45, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_45);

		// Angular distribution for energies 181000.0 < E <= 185000.0            
		double cos_angles_46[7] = {0.309017,0.325568,0.573576,0.601815,0.798636,0.920505,1.      };            
		double ang_probabilities_46[7] = {0.        ,0.17864869,0.15253458,0.15165116,0.15716655,0.17123955,
 0.18875948};            
		openmc::Tabular ang_dist_46(cos_angles_46, ang_probabilities_46, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_46);

		// Angular distribution for energies 185000.0 < E <= 189000.0            
		double cos_angles_47[6] = {0.325568,0.34202 ,0.615661,0.809017,0.927184,1.      };            
		double ang_probabilities_47[6] = {0.        ,0.21271438,0.17959818,0.18580953,0.20209402,0.21978389};            
		openmc::Tabular ang_dist_47(cos_angles_47, ang_probabilities_47, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_47);

		// Angular distribution for energies 189000.0 < E <= 193000.0            
		double cos_angles_48[7] = {0.34202 ,0.358368,0.615661,0.642788,0.819152,0.927184,1.      };            
		double ang_probabilities_48[7] = {0.        ,0.18180462,0.15341836,0.15281576,0.15772111,0.17029556,
 0.18394458};            
		openmc::Tabular ang_dist_48(cos_angles_48, ang_probabilities_48, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_48);

		// Angular distribution for energies 193000.0 < E <= 197000.0            
		double cos_angles_49[8] = {0.358368,0.374607,0.559193,0.62932 ,0.656059,0.829038,0.920505,1.      };            
		double ang_probabilities_49[8] = {0.        ,0.15759468,0.14100826,0.1327425 ,0.13175701,0.1358022 ,
 0.14471983,0.15637551};            
		openmc::Tabular ang_dist_49(cos_angles_49, ang_probabilities_49, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_49);

		// Angular distribution for energies 197000.0 < E <= 201000.0            
		double cos_angles_50[6] = {0.390731,0.406737,0.669131,0.848048,0.920505,1.      };            
		double ang_probabilities_50[6] = {0.        ,0.21780229,0.18222461,0.1882934 ,0.19818748,0.21349222};            
		openmc::Tabular ang_dist_50(cos_angles_50, ang_probabilities_50, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_50);

		// Angular distribution for energies 201000.0 < E <= 205000.0            
		double cos_angles_51[6] = {0.406737,0.422618,0.681998,0.857167,0.920505,1.      };            
		double ang_probabilities_51[6] = {0.        ,0.21974027,0.18299692,0.18857326,0.1968962 ,0.21179335};            
		openmc::Tabular ang_dist_51(cos_angles_51, ang_probabilities_51, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_51);

		// Angular distribution for energies 205000.0 < E <= 209000.0            
		double cos_angles_52[5] = {0.422618,0.438371,0.707107,0.87462 ,1.      };            
		double ang_probabilities_52[5] = {0.        ,0.27537106,0.22791255,0.23552746,0.26118893};            
		openmc::Tabular ang_dist_52(cos_angles_52, ang_probabilities_52, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_52);

		// Angular distribution for energies 209000.0 < E <= 213000.0            
		double cos_angles_53[5] = {0.45399 ,0.469472,0.71934 ,0.882948,1.      };            
		double ang_probabilities_53[5] = {0.        ,0.2759334 ,0.22883629,0.23585952,0.25937079};            
		openmc::Tabular ang_dist_53(cos_angles_53, ang_probabilities_53, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_53);

		// Angular distribution for energies 213000.0 < E <= 217000.0            
		double cos_angles_54[6] = {0.469472,0.48481 ,0.71934 ,0.743145,0.898794,1.      };            
		double ang_probabilities_54[6] = {0.        ,0.22573632,0.18750505,0.18600452,0.19208232,0.20867179};            
		openmc::Tabular ang_dist_54(cos_angles_54, ang_probabilities_54, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_54);

		// Angular distribution for energies 217000.0 < E <= 221000.0            
		double cos_angles_55[5] = {0.48481 ,0.5     ,0.75471 ,0.913545,1.      };            
		double ang_probabilities_55[5] = {0.        ,0.27971909,0.22923435,0.23685297,0.25419359};            
		openmc::Tabular ang_dist_55(cos_angles_55, ang_probabilities_55, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_55);

		// Angular distribution for energies 221000.0 < E <= 225000.0            
		double cos_angles_56[5] = {0.5     ,0.515038,0.766044,0.920505,1.      };            
		double ang_probabilities_56[5] = {0.        ,0.28180496,0.22986522,0.23666851,0.25166132};            
		openmc::Tabular ang_dist_56(cos_angles_56, ang_probabilities_56, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_56);

		// Angular distribution for energies 225000.0 < E <= 229000.0            
		double cos_angles_57[5] = {0.529919,0.544639,0.788011,0.93358 ,1.      };            
		double ang_probabilities_57[5] = {0.        ,0.28229731,0.23042142,0.23762577,0.24965549};            
		openmc::Tabular ang_dist_57(cos_angles_57, ang_probabilities_57, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_57);

		// Angular distribution for energies 229000.0 < E <= 233000.0            
		double cos_angles_58[5] = {0.544639,0.559193,0.798636,0.939693,1.      };            
		double ang_probabilities_58[5] = {0.        ,0.28448554,0.23102603,0.2374341 ,0.24705432};            
		openmc::Tabular ang_dist_58(cos_angles_58, ang_probabilities_58, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_58);

		// Angular distribution for energies 233000.0 < E <= 237000.0            
		double cos_angles_59[5] = {0.559193,0.573576,0.809017,0.945519,1.      };            
		double ang_probabilities_59[5] = {0.        ,0.28655781,0.23177778,0.23718715,0.24447726};            
		openmc::Tabular ang_dist_59(cos_angles_59, ang_probabilities_59, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_59);

		// Angular distribution for energies 237000.0 < E <= 241000.0            
		double cos_angles_60[4] = {0.573576,0.587785,0.829038,1.      };            
		double ang_probabilities_60[4] = {0.        ,0.37866061,0.30362686,0.31771253};            
		openmc::Tabular ang_dist_60(cos_angles_60, ang_probabilities_60, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_60);

		// Angular distribution for energies 241000.0 < E <= 245000.0            
		double cos_angles_61[5] = {0.601815,0.615661,0.669131,0.848048,1.      };            
		double ang_probabilities_61[5] = {0.        ,0.27923303,0.2636894 ,0.22413618,0.23294139};            
		openmc::Tabular ang_dist_61(cos_angles_61, ang_probabilities_61, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_61);

		// Angular distribution for energies 245000.0 < E <= 249000.0            
		double cos_angles_62[5] = {0.615661,0.62932 ,0.681998,0.857167,1.      };            
		double ang_probabilities_62[5] = {0.        ,0.28041599,0.26471346,0.2240352 ,0.23083535};            
		openmc::Tabular ang_dist_62(cos_angles_62, ang_probabilities_62, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_62);

		// Angular distribution for energies 249000.0 < E <= 253000.0            
		double cos_angles_63[5] = {0.62932 ,0.642788,0.707107,0.87462 ,1.      };            
		double ang_probabilities_63[5] = {0.        ,0.28265409,0.26356625,0.22387078,0.22990888};            
		openmc::Tabular ang_dist_63(cos_angles_63, ang_probabilities_63, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_63);

		// Angular distribution for energies 253000.0 < E <= 257000.0            
		double cos_angles_64[5] = {0.642788,0.656059,0.882948,0.913545,1.      };            
		double ang_probabilities_64[5] = {0.        ,0.29612085,0.23371867,0.23204203,0.23811846};            
		openmc::Tabular ang_dist_64(cos_angles_64, ang_probabilities_64, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_64);

		// Angular distribution for energies 257000.0 < E <= 261000.0            
		double cos_angles_65[6] = {0.669131,0.681998,0.743145,0.898794,0.927184,1.      };            
		double ang_probabilities_65[6] = {0.        ,0.23209511,0.21592141,0.18345894,0.18218325,0.18634129};            
		openmc::Tabular ang_dist_65(cos_angles_65, ang_probabilities_65, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_65);

		// Angular distribution for energies 261000.0 < E <= 265000.0            
		double cos_angles_66[6] = {0.681998,0.694658,0.75471 ,0.913545,0.939693,1.      };            
		double ang_probabilities_66[6] = {0.        ,0.23343362,0.21702138,0.18293969,0.18156634,0.18503897};            
		openmc::Tabular ang_dist_66(cos_angles_66, ang_probabilities_66, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_66);

		// Angular distribution for energies 265000.0 < E <= 269000.0            
		double cos_angles_67[6] = {0.694658,0.707107,0.766044,0.927184,0.951057,1.      };            
		double ang_probabilities_67[6] = {0.        ,0.23477464,0.21820297,0.18250901,0.18091232,0.18360106};            
		openmc::Tabular ang_dist_67(cos_angles_67, ang_probabilities_67, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_67);

		// Angular distribution for energies 269000.0 < E <= 273000.0            
		double cos_angles_68[6] = {0.707107,0.71934 ,0.788011,0.939693,0.965926,1.      };            
		double ang_probabilities_68[6] = {0.        ,0.23676105,0.21733568,0.18268199,0.18072228,0.182499  };            
		openmc::Tabular ang_dist_68(cos_angles_68, ang_probabilities_68, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_68);

		// Angular distribution for energies 273000.0 < E <= 277000.0            
		double cos_angles_69[5] = {0.731354,0.743145,0.798636,0.951057,1.      };            
		double ang_probabilities_69[5] = {0.        ,0.2881852 ,0.2673733 ,0.22329322,0.22114828};            
		openmc::Tabular ang_dist_69(cos_angles_69, ang_probabilities_69, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_69);

		// Angular distribution for energies 277000.0 < E <= 281000.0            
		double cos_angles_70[5] = {0.743145,0.75471 ,0.819152,0.961262,1.      };            
		double ang_probabilities_70[5] = {0.        ,0.29043215,0.26613974,0.22376148,0.21966663};            
		openmc::Tabular ang_dist_70(cos_angles_70, ang_probabilities_70, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_70);

		// Angular distribution for energies 281000.0 < E <= 285000.0            
		double cos_angles_71[5] = {0.75471 ,0.766044,0.848048,0.97437 ,1.      };            
		double ang_probabilities_71[5] = {0.        ,0.29350641,0.26284489,0.22401194,0.21963676};            
		openmc::Tabular ang_dist_71(cos_angles_71, ang_probabilities_71, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_71);

		// Angular distribution for energies 285000.0 < E <= 289000.0            
		double cos_angles_72[4] = {0.777146,0.788011,0.848048,1.      };            
		double ang_probabilities_72[4] = {0.        ,0.37461394,0.34301966,0.2823664 };            
		openmc::Tabular ang_dist_72(cos_angles_72, ang_probabilities_72, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_72);

		// Angular distribution for energies 289000.0 < E <= 293000.0            
		double cos_angles_73[4] = {0.788011,0.798636,0.866025,1.      };            
		double ang_probabilities_73[4] = {0.        ,0.37573495,0.3400362 ,0.28422885};            
		openmc::Tabular ang_dist_73(cos_angles_73, ang_probabilities_73, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_73);

		// Angular distribution for energies 293000.0 < E <= 297000.0            
		double cos_angles_74[4] = {0.809017,0.819152,0.87462 ,1.      };            
		double ang_probabilities_74[4] = {0.        ,0.37205069,0.3407447 ,0.28720461};            
		openmc::Tabular ang_dist_74(cos_angles_74, ang_probabilities_74, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_74);

		// Angular distribution for energies 297000.0 < E <= 301000.0            
		double cos_angles_75[4] = {0.819152,0.829038,0.891007,1.      };            
		double ang_probabilities_75[4] = {0.        ,0.37248825,0.33730656,0.29020519};            
		openmc::Tabular ang_dist_75(cos_angles_75, ang_probabilities_75, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_75);

		// Angular distribution for energies 301000.0 < E <= 305000.0            
		double cos_angles_76[4] = {0.838671,0.848048,0.906308,1.      };            
		double ang_probabilities_76[4] = {0.        ,0.37021726,0.33569952,0.29408323};            
		openmc::Tabular ang_dist_76(cos_angles_76, ang_probabilities_76, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_76);

		// Angular distribution for energies 305000.0 < E <= 309000.0            
		double cos_angles_77[4] = {0.848048,0.857167,0.920505,1.      };            
		double ang_probabilities_77[4] = {0.        ,0.37082123,0.3328712 ,0.29630757};            
		openmc::Tabular ang_dist_77(cos_angles_77, ang_probabilities_77, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_77);

		// Angular distribution for energies 309000.0 < E <= 313000.0            
		double cos_angles_78[4] = {0.866025,0.87462 ,0.927184,1.      };            
		double ang_probabilities_78[4] = {0.        ,0.36728995,0.33399944,0.29871061};            
		openmc::Tabular ang_dist_78(cos_angles_78, ang_probabilities_78, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_78);

		// Angular distribution for energies 313000.0 < E <= 317000.0            
		double cos_angles_79[4] = {0.87462 ,0.882948,0.939693,1.      };            
		double ang_probabilities_79[4] = {0.        ,0.36764202,0.3314002 ,0.30095778};            
		openmc::Tabular ang_dist_79(cos_angles_79, ang_probabilities_79, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_79);

		// Angular distribution for energies 317000.0 < E <= 321000.0            
		double cos_angles_80[4] = {0.891007,0.898794,0.951057,1.      };            
		double ang_probabilities_80[4] = {0.        ,0.3651196 ,0.33038996,0.30449044};            
		openmc::Tabular ang_dist_80(cos_angles_80, ang_probabilities_80, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_80);

		// Angular distribution for energies 321000.0 < E <= 325000.0            
		double cos_angles_81[3] = {0.906308,0.913545,1.      };            
		double ang_probabilities_81[3] = {0.        ,0.54072644,0.45927356};            
		openmc::Tabular ang_dist_81(cos_angles_81, ang_probabilities_81, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_81);

		// Angular distribution for energies 325000.0 < E <= 329000.0            
		double cos_angles_82[3] = {0.920505,0.927184,1.      };            
		double ang_probabilities_82[3] = {0.        ,0.53622071,0.46377929};            
		openmc::Tabular ang_dist_82(cos_angles_82, ang_probabilities_82, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_82);

		// Angular distribution for energies 329000.0 < E <= 333000.0            
		double cos_angles_83[3] = {0.93358 ,0.939693,1.      };            
		double ang_probabilities_83[3] = {0.        ,0.53161267,0.46838733};            
		openmc::Tabular ang_dist_83(cos_angles_83, ang_probabilities_83, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_83);

		// Angular distribution for energies 333000.0 < E <= 337000.0            
		double cos_angles_84[3] = {0.945519,0.951057,1.      };            
		double ang_probabilities_84[3] = {0.        ,0.52669057,0.47330943};            
		openmc::Tabular ang_dist_84(cos_angles_84, ang_probabilities_84, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_84);

		// Angular distribution for energies 337000.0 < E <= 341000.0            
		double cos_angles_85[3] = {0.961262,0.965926,1.      };            
		double ang_probabilities_85[3] = {0.        ,0.51902251,0.48097749};            
		openmc::Tabular ang_dist_85(cos_angles_85, ang_probabilities_85, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_85);

		// Angular distribution for energies 341000.0 < E <= 345000.0            
		double cos_angles_86[3] = {0.97437 ,0.978148,1.      };            
		double ang_probabilities_86[3] = {0.        ,0.51169955,0.48830045};            
		openmc::Tabular ang_dist_86(cos_angles_86, ang_probabilities_86, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_86);

		// Angular distribution for energies 345000.0 < E <= 349000.0            
		double cos_angles_87[3] = {0.987688,0.990268,1.      };            
		double ang_probabilities_87[3] = {0.        ,0.50496671,0.49503329};            
		openmc::Tabular ang_dist_87(cos_angles_87, ang_probabilities_87, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_87);

		// Angular distribution for energies 349000.0 < E <= 351000.0            
		double cos_angles_88[3] = {0.99863 ,0.999391,1.      };            
		double ang_probabilities_88[3] = {0.        ,0.50030841,0.49969159};            
		openmc::Tabular ang_dist_88(cos_angles_88, ang_probabilities_88, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_88);

		// Choose angular distribution depending on sampled energy    
		for (int n = 0; n < 88; n++) {    
			if (energy < edges[n]) {     
				mu = ang_dists[n].sample(seed);    
				break;
			}
		}

		// Convert sampled mu to angle    
		theta = std::acos(mu);    
		// Sample phi in range [0,2pi];    
		phi = 2.0 * M_PI * openmc::prn(seed);    

		// Set directional vector    
		particle.u = {std::sin(theta)*std::cos(phi), std::sin(theta)*std::sin(phi), mu};

		// Sample particle starting position
		openmc::Normal r_dist(0, 1.7);    
		double x_pos = r_dist.sample(seed);    
		double y_pos = r_dist.sample(seed);    
		// Set position of particle    
		particle.r = {x_pos, y_pos - 42, 0.0};

		// Return particle    
		return particle;    
	}    
};

// Function to create unique pointer to an instance of this class when generated via a plugin call using dlopen/dlsym    
extern "C" std::unique_ptr<Li_source> openmc_create_source(std::string parameters) {    
	return std::make_unique<Li_source>();    
}
