/*
Source file for OpenMC generated by MCNP_to_OpenMC.py script by Max Conroy.    

Distributions based on MCNP SDEF file by Daniel Minsky.    

Details:
	Generated on 19-03-2024.    

For more information, please contact m.j.conroy@pgr.bham.ac.uk.
*/
#include <memory>
#include <cmath>
#include <vector>
#include <iostream>
#include "openmc/random_lcg.h"
#include "openmc/source.h"
#include "openmc/particle.h"
#include "openmc/distribution.h"

// Create new source class which inherits from openmc::Source    
class Li_source : public openmc::Source {

	// Define a function called "sample" to generate neutrons
	openmc::SourceSite sample(uint64_t* seed) const {

		openmc::SourceSite particle;
		// Define particle type
		particle.particle = openmc::ParticleType::neutron;    
		// Define particle weight
		particle.wgt = 2.828849e+11;

		// Initialise required variables    
		double energy {0.0};
		double mu {0.0};    
		double theta {0.0};
		double phi {0.0};    
		double pos_r {0.0};
		double pos_ang {0.0};

		// Define energies and probabilities for distribution    
		double energies[177] = {     0.,  1000.,  2000.,  3000.,  4000.,  6000.,  8000., 11000., 18000.,
  23000., 29000., 36000., 46000., 73000.,111000.,133000.,135000.,139000.,
 150000.,152000.,155000.,157000.,162000.,167000.,170000.,172000.,175000.,
 180000.,181000.,183000.,184000.,186000.,187000.,189000.,192000.,194000.,
 195000.,197000.,198000.,200000.,201000.,204000.,205000.,207000.,208000.,
 210000.,211000.,213000.,214000.,216000.,217000.,219000.,220000.,223000.,
 224000.,226000.,227000.,229000.,230000.,233000.,234000.,236000.,237000.,
 239000.,240000.,243000.,244000.,246000.,247000.,250000.,251000.,253000.,
 254000.,257000.,258000.,260000.,261000.,264000.,265000.,267000.,268000.,
 271000.,272000.,274000.,275000.,278000.,279000.,281000.,282000.,285000.,
 286000.,288000.,289000.,292000.,293000.,295000.,296000.,299000.,300000.,
 302000.,303000.,306000.,307000.,309000.,310000.,312000.,313000.,316000.,
 317000.,319000.,320000.,322000.,323000.,326000.,327000.,329000.,330000.,
 332000.,333000.,335000.,336000.,338000.,339000.,342000.,343000.,345000.,
 346000.,348000.,349000.,351000.,352000.,354000.,355000.,356000.,357000.,
 359000.,360000.,362000.,363000.,365000.,366000.,367000.,368000.,370000.,
 371000.,372000.,373000.,375000.,376000.,377000.,378000.,379000.,380000.,
 381000.,382000.,383000.,384000.,385000.,386000.,387000.,388000.,389000.,
 390000.,391000.,392000.,393000.,395000.,396000.,398000.,399000.,401000.,
 403000.,404000.,405000.,406000.,407000.,408000.};    
		double E_probabilities[177] = {0.00000000e+00,3.50208433e-03,4.96604444e-03,6.08843527e-03,
 7.03170806e-03,8.59975027e-03,9.90544711e-03,1.15679245e-02,
 1.46030868e-02,1.62856239e-02,1.78743628e-02,1.92147976e-02,
 2.06179490e-02,2.29928205e-02,1.82825262e-02,1.60543352e-02,
 1.56064156e-02,1.54074004e-02,1.40330682e-02,1.40459556e-02,
 1.35668461e-02,1.35784801e-02,1.28511382e-02,1.26227518e-02,
 1.21289977e-02,1.21385670e-02,1.16432372e-02,1.14120012e-02,
 1.11613806e-02,1.11715942e-02,1.09208462e-02,1.09314860e-02,
 1.06807570e-02,1.06917994e-02,1.01972779e-02,1.02079631e-02,
 9.95901325e-03,9.96997512e-03,9.72159199e-03,9.73277351e-03,
 9.48509033e-03,9.50289641e-03,9.25513854e-03,9.26768480e-03,
 9.02092414e-03,9.03366369e-03,8.78806716e-03,8.80103953e-03,
 8.55678138e-03,8.57003491e-03,8.32728794e-03,8.34086947e-03,
 8.09980206e-03,8.12154715e-03,7.88142863e-03,7.89687863e-03,
 7.65876328e-03,7.67465111e-03,7.43869124e-03,7.46404587e-03,
 7.22947564e-03,7.24737983e-03,7.01522572e-03,7.03353699e-03,
 6.80390589e-03,6.83273388e-03,6.60478236e-03,6.62481859e-03,
 6.39956873e-03,6.43076159e-03,6.20735091e-03,6.22888074e-03,
 6.00838259e-03,6.04179535e-03,5.82336627e-03,5.84642632e-03,
 5.63115430e-03,5.66701247e-03,5.45406726e-03,5.47886252e-03,
 5.26931305e-03,5.30793145e-03,5.10094454e-03,5.12768148e-03,
 4.92429972e-03,4.96591411e-03,4.76524718e-03,4.79390385e-03,
 4.59691382e-03,4.64098533e-03,4.44663840e-03,4.47647237e-03,
 4.28569836e-03,4.33067043e-03,4.14232865e-03,4.17227245e-03,
 3.98744503e-03,4.03224431e-03,3.84989158e-03,3.87975484e-03,
 3.70105558e-03,3.74601887e-03,3.56997588e-03,3.60011589e-03,
 3.42783473e-03,3.45770238e-03,3.28919623e-03,3.33426348e-03,
 3.16849120e-03,3.19870004e-03,3.03671887e-03,3.06665096e-03,
 2.90845944e-03,2.95363505e-03,2.79820377e-03,2.82848876e-03,
 2.67682809e-03,2.70680850e-03,2.55888330e-03,2.58851227e-03,
 2.44426397e-03,2.47345804e-03,2.33280756e-03,2.37636803e-03,
 2.23821715e-03,2.26711249e-03,2.13252868e-03,2.16105502e-03,
 2.03007635e-03,2.05835815e-03,1.93098756e-03,1.95907460e-03,
 1.83527548e-03,1.84900490e-03,1.72963240e-03,1.75642206e-03,
 1.64045556e-03,1.66688500e-03,1.55423225e-03,1.58021800e-03,
 1.47079406e-03,1.48336522e-03,1.37801135e-03,1.40228546e-03,
 1.30001148e-03,1.31170419e-03,1.21333496e-03,1.23582275e-03,
 1.14040925e-03,1.15119994e-03,1.05954694e-03,1.06975307e-03,
 9.81781366e-04,9.91412611e-04,9.07046927e-04,9.16112068e-04,
 8.35282560e-04,8.43789797e-04,7.66431304e-04,7.74388543e-04,
 7.00442346e-04,7.07856910e-04,6.37270439e-04,6.44149649e-04,
 5.76877511e-04,5.83228395e-04,4.59126742e-04,4.64315252e-04,
 3.54299293e-04,3.58411238e-04,2.62254004e-04,1.80856928e-04,
 1.45654070e-04,1.14120891e-04,6.14058689e-05,2.47315053e-05,
 0.00000000e+00};
		// Define energy distribution
		openmc::Tabular E_dist(energies, E_probabilities, 177, openmc::Interpolation::lin_lin);
		// Sample energy from distribution
		energy = E_dist.sample(seed);
		particle.E = energy;

		// Define energy values for bin edges to choose angular distribution    
		double edges[102] = {  5000.,  9000., 13000., 17000., 21000., 25000., 29000., 33000., 37000.,
  41000., 45000., 49000., 53000., 57000., 61000., 65000., 69000., 73000.,
  77000., 81000., 85000., 89000., 93000., 97000.,101000.,105000.,109000.,
 113000.,117000.,121000.,125000.,129000.,133000.,137000.,141000.,145000.,
 149000.,153000.,157000.,161000.,165000.,169000.,173000.,177000.,181000.,
 185000.,189000.,193000.,197000.,201000.,205000.,209000.,213000.,217000.,
 221000.,225000.,229000.,233000.,237000.,241000.,245000.,249000.,253000.,
 257000.,261000.,265000.,269000.,273000.,277000.,281000.,285000.,289000.,
 293000.,297000.,301000.,305000.,309000.,313000.,317000.,321000.,325000.,
 329000.,333000.,337000.,341000.,345000.,349000.,353000.,357000.,361000.,
 365000.,369000.,373000.,377000.,381000.,385000.,389000.,393000.,397000.,
 401000.,405000.,408000.};

		// Create vector to hold angular distributions        
		std::vector<openmc::Tabular> ang_dists;

		// Angular distribution for energies 0.0 < E <= 5000.0            
		double cos_angles_1[6] = {-1.       ,-0.052336 ,-0.0348995, 0.515038 , 0.766044 , 1.       };            
		double ang_probabilities_1[6] = {0.13454542,0.15214883,0.1478466 ,0.17108408,0.1870698 ,0.20730527};            
		openmc::Tabular ang_dist_1(cos_angles_1, ang_probabilities_1, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_1);

		// Angular distribution for energies 5000.0 < E <= 9000.0            
		double cos_angles_2[9] = {-1.      ,-0.358368, 0.104528, 0.121869, 0.374607, 0.601815, 0.809017,
  0.906308, 1.      };            
		double ang_probabilities_2[9] = {0.07824939,0.08623586,0.09513689,0.09266001,0.10218601,0.11458028,
 0.13148015,0.14265184,0.15681957};            
		openmc::Tabular ang_dist_2(cos_angles_2, ang_probabilities_2, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_2);

		// Angular distribution for energies 9000.0 < E <= 13000.0            
		double cos_angles_3[11] = {-1.      ,-0.601815,-0.139173, 0.190809, 0.207912, 0.438371, 0.656059,
  0.75471 , 0.838671, 0.927184, 1.      };            
		double ang_probabilities_3[11] = {0.06040601,0.06180932,0.06806523,0.07454513,0.07268065,0.08155196,
 0.09461814,0.10320713,0.11278949,0.12669271,0.14363425};            
		openmc::Tabular ang_dist_3(cos_angles_3, ang_probabilities_3, 11, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_3);

		// Angular distribution for energies 13000.0 < E <= 17000.0            
		double cos_angles_4[14] = {-1.      ,-0.642788,-0.469472,-0.052336, 0.258819, 0.275637, 0.5     ,
  0.601815, 0.694658, 0.788011, 0.866025, 0.939693, 0.970296, 1.      };            
		double ang_probabilities_4[14] = {0.04428786,0.04432437,0.04502328,0.04972589,0.05496835,0.05367896,
 0.06147388,0.06655697,0.07256619,0.08067927,0.0901531 ,0.10345174,
 0.11137646,0.12173368};            
		openmc::Tabular ang_dist_4(cos_angles_4, ang_probabilities_4, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_4);

		// Angular distribution for energies 17000.0 < E <= 21000.0            
		double cos_angles_5[14] = {-1.       ,-0.374607 , 0.0174524, 0.309017 , 0.325568 , 0.529919 ,
  0.62932  , 0.71934  , 0.809017 , 0.882948 , 0.920505 , 0.951057 ,
  0.978148 , 1.       };            
		double ang_probabilities_5[14] = {0.03990272,0.04011931,0.04444427,0.04943686,0.04827009,0.05552168,
 0.06067785,0.06690758,0.07557226,0.08613356,0.09375038,0.10204363,
 0.11231831,0.12490148};            
		openmc::Tabular ang_dist_5(cos_angles_5, ang_probabilities_5, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_5);

		// Angular distribution for energies 21000.0 < E <= 25000.0            
		double cos_angles_6[17] = {-1.       ,-0.731354 ,-0.292372 ,-0.0348995, 0.156434 , 0.358368 ,
  0.374607 , 0.573576 , 0.669131 , 0.75471  , 0.838671 , 0.906308 ,
  0.93358  , 0.961262 , 0.984808 , 0.992546 , 1.       };            
		double ang_probabilities_6[17] = {0.03169453,0.03093019,0.03124084,0.03337422,0.03565515,0.03883935,
 0.03797669,0.04429153,0.04885833,0.05446193,0.06243058,0.07247867,
 0.078426  ,0.0867924 ,0.09794333,0.10350369,0.11110257};            
		openmc::Tabular ang_dist_6(cos_angles_6, ang_probabilities_6, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_6);

		// Angular distribution for energies 25000.0 < E <= 29000.0            
		double cos_angles_7[20] = {-1.       ,-0.601815 ,-0.207912 , 0.0348995, 0.207912 , 0.390731 ,
  0.406737 , 0.5      , 0.601815 , 0.694658 , 0.777146 , 0.857167 ,
  0.891007 , 0.920505 , 0.945519 , 0.970296 , 0.981627 , 0.990268 ,
  0.996195 , 1.       };            
		double ang_probabilities_7[20] = {0.02494149,0.02436464,0.02463899,0.02637101,0.02816218,0.03069123,
 0.02993536,0.03212048,0.03525665,0.0391538 ,0.04398856,0.05097295,
 0.05519317,0.0600044 ,0.0655054 ,0.07352605,0.07903507,0.0850939 ,
 0.09158228,0.09946239};            
		openmc::Tabular ang_dist_7(cos_angles_7, ang_probabilities_7, 20, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_7);

		// Angular distribution for energies 29000.0 < E <= 33000.0            
		double cos_angles_8[22] = {-1.       ,-0.777146 ,-0.5      ,-0.139173 , 0.0871557, 0.258819 ,
  0.438371 , 0.45399  , 0.544639 , 0.62932  , 0.71934  , 0.798636 ,
  0.866025 , 0.898794 , 0.927184 , 0.951057 , 0.97437  , 0.984808 ,
  0.992546 , 0.997564 , 0.999391 , 1.       };            
		double ang_probabilities_8[22] = {0.02156424,0.02172235,0.02117634,0.02142946,0.02291359,0.0246025 ,
 0.0269432 ,0.02637663,0.02844925,0.03096794,0.03458313,0.03909581,
 0.04474885,0.04861829,0.05305473,0.05816316,0.06569414,0.07094269,
 0.07682636,0.08336945,0.0879134 ,0.09084448};            
		openmc::Tabular ang_dist_8(cos_angles_8, ang_probabilities_8, 22, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_8);

		// Angular distribution for energies 33000.0 < E <= 37000.0            
		double cos_angles_9[21] = {-1.       ,-0.857167 ,-0.669131 ,-0.406737 ,-0.0871557, 0.121869 ,
  0.309017 , 0.469472 , 0.48481  , 0.573576 , 0.656059 , 0.731354 ,
  0.798636 , 0.866025 , 0.898794 , 0.927184 , 0.951057 , 0.970296 ,
  0.987688 , 0.994522 , 1.       };            
		double ang_probabilities_9[21] = {0.02676983,0.02571272,0.02597223,0.02534233,0.02563936,0.02727756,
 0.02966362,0.03240188,0.03168706,0.03429142,0.03746407,0.04131152,
 0.04597011,0.05266951,0.05724195,0.06245996,0.06841719,0.07519719,
 0.08481678,0.0909088 ,0.09878491};            
		openmc::Tabular ang_dist_9(cos_angles_9, ang_probabilities_9, 21, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_9);

		// Angular distribution for energies 37000.0 < E <= 41000.0            
		double cos_angles_10[19] = {-1.      ,-0.75471 ,-0.573576,-0.325568,-0.052336, 0.121869, 0.325568,
  0.5     , 0.515038, 0.669131, 0.743145, 0.809017, 0.866025, 0.920505,
  0.945519, 0.965926, 0.984808, 0.992546, 1.      };            
		double ang_probabilities_10[19] = {0.03113435,0.02930209,0.02959882,0.02891027,0.0292154 ,0.0305467 ,
 0.03358087,0.03716709,0.03632585,0.04252872,0.04696842,0.05233418,
 0.05880853,0.0680483 ,0.07425914,0.08116456,0.09051954,0.09606135,
 0.10352584};            
		openmc::Tabular ang_dist_10(cos_angles_10, ang_probabilities_10, 19, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_10);

		// Angular distribution for energies 41000.0 < E <= 45000.0            
		double cos_angles_11[19] = {-1.       ,-0.829038 ,-0.681998 ,-0.5      ,-0.275637 , 0.0174524,
  0.190809 , 0.374607 , 0.529919 , 0.544639 , 0.656059 , 0.766044 ,
  0.809017 , 0.857167 , 0.898794 , 0.939693 , 0.97437  , 0.987688 ,
  1.       };            
		double ang_probabilities_11[19] = {0.03451156,0.03373499,0.03216283,0.03244559,0.03171162,0.03214908,
 0.03391346,0.03721323,0.0410143 ,0.04007892,0.04496301,0.05219131,
 0.05610939,0.06171787,0.06820384,0.07722879,0.08922592,0.09617335,
 0.10525093};            
		openmc::Tabular ang_dist_11(cos_angles_11, ang_probabilities_11, 19, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_11);

		// Angular distribution for energies 45000.0 < E <= 49000.0            
		double cos_angles_12[17] = {-1.       ,-0.75471  ,-0.601815 ,-0.422618 ,-0.224951 , 0.0697565,
  0.207912 , 0.406737 , 0.559193 , 0.573576 , 0.656059 , 0.766044 ,
  0.857167 , 0.898794 , 0.939693 , 0.97437  , 1.       };            
		double ang_probabilities_12[17] = {0.04201265,0.04075247,0.03874481,0.03907951,0.03824027,0.03884066,
 0.04051368,0.04499562,0.04977784,0.04865046,0.05307031,0.06150179,
 0.07251724,0.07991417,0.09000499,0.10288577,0.11849776};            
		openmc::Tabular ang_dist_12(cos_angles_12, ang_probabilities_12, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_12);

		// Angular distribution for energies 49000.0 < E <= 53000.0            
		double cos_angles_13[17] = {-1.      ,-0.669131,-0.515038,-0.358368,-0.104528, 0.104528, 0.207912,
  0.422618, 0.587785, 0.601815, 0.656059, 0.75471 , 0.848048, 0.891007,
  0.93358 , 0.970296, 1.      };            
		double ang_probabilities_13[17] = {0.04394557,0.04184303,0.03976015,0.04017836,0.03938628,0.03997059,
 0.04106446,0.04604156,0.05158309,0.05043658,0.05346249,0.06078362,
 0.07132165,0.07832592,0.08775873,0.09957157,0.11456635};            
		openmc::Tabular ang_dist_13(cos_angles_13, ang_probabilities_13, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_13);

		// Angular distribution for energies 53000.0 < E <= 57000.0            
		double cos_angles_14[18] = {-1.       ,-0.898794 ,-0.62932  ,-0.438371 ,-0.292372 ,-0.0697565,
  0.139173 , 0.241922 , 0.45399  , 0.615661 , 0.62932  , 0.656059 ,
  0.75471  , 0.848048 , 0.891007 , 0.93358  , 0.970296 , 1.       };            
		double ang_probabilities_14[18] = {0.04275479,0.0428542 ,0.04105999,0.03873595,0.03916027,0.03840498,
 0.03902032,0.04007208,0.04511191,0.05070871,0.04961325,0.05108336,
 0.05795943,0.06777549,0.07421767,0.08275061,0.09312737,0.10558962};            
		openmc::Tabular ang_dist_14(cos_angles_14, ang_probabilities_14, 18, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_14);

		// Angular distribution for energies 57000.0 < E <= 61000.0            
		double cos_angles_15[16] = {-1.       ,-0.819152 ,-0.559193 ,-0.390731 ,-0.241922 ,-0.0348995,
  0.258819 , 0.469472 , 0.642788 , 0.656059 , 0.75471  , 0.848048 ,
  0.891007 , 0.927184 , 0.965926 , 1.       };            
		double ang_probabilities_15[16] = {0.0485494 ,0.04809041,0.04602827,0.04346862,0.04392206,0.04308522,
 0.04472287,0.05038909,0.05736405,0.05616873,0.063588  ,0.07409591,
 0.08090951,0.08828049,0.09888107,0.11245631};            
		openmc::Tabular ang_dist_15(cos_angles_15, ang_probabilities_15, 16, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_15);

		// Angular distribution for energies 61000.0 < E <= 65000.0            
		double cos_angles_16[15] = {-1.       ,-0.5      ,-0.325568 ,-0.190809 , 0.0174524, 0.275637 ,
  0.438371 , 0.544639 , 0.669131 , 0.681998 , 0.777146 , 0.857167 ,
  0.93358  , 0.970296 , 1.       };            
		double ang_probabilities_16[15] = {0.05411227,0.0503595 ,0.0474837 ,0.04801886,0.04716145,0.04871979,
 0.05316923,0.0571726 ,0.06328382,0.06201872,0.07027177,0.08035747,
 0.09507689,0.10556825,0.11722567};            
		openmc::Tabular ang_dist_16(cos_angles_16, ang_probabilities_16, 15, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_16);

		// Angular distribution for energies 65000.0 < E <= 69000.0            
		double cos_angles_17[17] = {-1.      ,-0.819152,-0.681998,-0.438371,-0.275637,-0.139173, 0.052336,
  0.309017, 0.469472, 0.573576, 0.694658, 0.707107, 0.788011, 0.866025,
  0.939693, 0.970296, 1.      };            
		double ang_probabilities_17[17] = {0.05037082,0.0482151 ,0.04800393,0.04586328,0.04327094,0.04375271,
 0.04299902,0.04451371,0.04872073,0.05250008,0.05820368,0.05709053,
 0.06366622,0.07260512,0.08528017,0.09274214,0.10220181};            
		openmc::Tabular ang_dist_17(cos_angles_17, ang_probabilities_17, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_17);

		// Angular distribution for energies 69000.0 < E <= 73000.0            
		double cos_angles_18[17] = {-1.       ,-0.75471  ,-0.62932  ,-0.374607 ,-0.224951 ,-0.104528 ,
  0.0871557, 0.325568 , 0.45399  , 0.587785 , 0.71934  , 0.731354 ,
  0.809017 , 0.87462  , 0.939693 , 0.970296 , 1.       };            
		double ang_probabilities_18[17] = {0.0519768 ,0.04874332,0.04854984,0.04618861,0.0436551 ,0.04415479,
 0.04341828,0.0448229 ,0.04785822,0.05281533,0.05928998,0.05820472,
 0.06489313,0.07261921,0.08345736,0.09038145,0.09897097};            
		openmc::Tabular ang_dist_18(cos_angles_18, ang_probabilities_18, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_18);

		// Angular distribution for energies 73000.0 < E <= 77000.0            
		double cos_angles_19[17] = {-0.965926,-0.961262,-0.694658,-0.573576,-0.325568,-0.190809,-0.052336,
  0.121869, 0.34202 , 0.469472, 0.615661, 0.743145, 0.75471 , 0.819152,
  0.882948, 0.945519, 1.      };            
		double ang_probabilities_19[17] = {0.        ,0.05801126,0.05392463,0.05368065,0.05102706,0.04827785,
 0.0487499 ,0.04797475,0.04942948,0.05258694,0.05880642,0.06609146,
 0.06492842,0.07120577,0.07945068,0.09070526,0.10514947};            
		openmc::Tabular ang_dist_19(cos_angles_19, ang_probabilities_19, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_19);

		// Angular distribution for energies 77000.0 < E <= 81000.0            
		double cos_angles_20[17] = {-0.906308 ,-0.898794 ,-0.642788 ,-0.515038 ,-0.275637 ,-0.139173 ,
 -0.0174524, 0.156434 , 0.374607 , 0.5      , 0.642788 , 0.766044 ,
  0.777146 , 0.838671 , 0.891007 , 0.945519 , 1.       };            
		double ang_probabilities_20[17] = {0.        ,0.05845215,0.05428752,0.05391985,0.05120055,0.04839511,
 0.04893359,0.04819274,0.04978329,0.05311604,0.05954711,0.06697481,
 0.06583189,0.07211645,0.07900065,0.08845236,0.1017959 };            
		openmc::Tabular ang_dist_20(cos_angles_20, ang_probabilities_20, 17, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_20);

		// Angular distribution for energies 81000.0 < E <= 85000.0            
		double cos_angles_21[18] = {-0.848048 ,-0.838671 ,-0.587785 ,-0.469472 ,-0.224951 ,-0.104528 ,
  0.0348995, 0.190809 , 0.390731 , 0.45399  , 0.529919 , 0.669131 ,
  0.788011 , 0.798636 , 0.857167 , 0.906308 , 0.956305 , 1.       };            
		double ang_probabilities_21[18] = {0.        ,0.05582845,0.05175492,0.05141731,0.04866447,0.04611172,
 0.04656148,0.04590437,0.04735   ,0.04846633,0.05089797,0.05718815,
 0.06434454,0.06326597,0.06919154,0.07553343,0.08388494,0.09363442};            
		openmc::Tabular ang_dist_21(cos_angles_21, ang_probabilities_21, 18, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_21);

		// Angular distribution for energies 85000.0 < E <= 89000.0            
		double cos_angles_22[16] = {-0.788011 ,-0.777146 ,-0.529919 ,-0.422618 ,-0.190809 ,-0.052336 ,
  0.0697565, 0.224951 , 0.406737 , 0.529919 , 0.681998 , 0.798636 ,
  0.809017 , 0.906308 , 0.956305 , 1.       };            
		double ang_probabilities_22[16] = {0.        ,0.06399468,0.05921878,0.058893  ,0.05579968,0.0526334 ,
 0.05325397,0.05254828,0.05413883,0.05734817,0.06524119,0.07361498,
 0.07197061,0.084323  ,0.09332986,0.10369158};            
		openmc::Tabular ang_dist_22(cos_angles_22, ang_probabilities_22, 16, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_22);

		// Angular distribution for energies 89000.0 < E <= 93000.0            
		double cos_angles_23[16] = {-0.743145 ,-0.731354 ,-0.48481  ,-0.374607 ,-0.139173 ,-0.0174524,
  0.104528 , 0.258819 , 0.422618 , 0.48481  , 0.559193 , 0.707107 ,
  0.819152 , 0.829038 , 0.920505 , 1.       };            
		double ang_probabilities_23[16] = {0.        ,0.06694388,0.06173692,0.06129822,0.05784578,0.05473123,
 0.05536626,0.05468931,0.05628263,0.05738474,0.06005073,0.06845965,
 0.07722759,0.07549406,0.08792979,0.10455921};            
		openmc::Tabular ang_dist_23(cos_angles_23, ang_probabilities_23, 16, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_23);

		// Angular distribution for energies 93000.0 < E <= 97000.0            
		double cos_angles_24[16] = {-0.681998 ,-0.669131 ,-0.438371 ,-0.325568 ,-0.104528 , 0.0174524,
  0.139173 , 0.275637 , 0.438371 , 0.515038 , 0.587785 , 0.731354 ,
  0.848048 , 0.857167 , 0.927184 , 1.       };            
		double ang_probabilities_24[16] = {0.        ,0.06691339,0.06181339,0.06128288,0.05788885,0.0546938 ,
 0.05532294,0.05464552,0.05623993,0.05765169,0.06046342,0.0690487 ,
 0.07851509,0.07712359,0.0869115 ,0.10148531};            
		openmc::Tabular ang_dist_24(cos_angles_24, ang_probabilities_24, 16, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_24);

		// Angular distribution for energies 97000.0 < E <= 101000.0            
		double cos_angles_25[16] = {-0.642788 ,-0.62932  ,-0.406737 ,-0.292372 ,-0.0871557, 0.052336 ,
  0.173648 , 0.309017 , 0.406737 , 0.544639 , 0.669131 , 0.766044 ,
  0.866025 , 0.87462  , 0.939693 , 1.       };            
		double ang_probabilities_25[16] = {0.        ,0.06706959,0.06187024,0.06117354,0.05796985,0.05443692,
 0.0550674 ,0.05445135,0.05537796,0.05772432,0.06374437,0.07022127,
 0.07878404,0.07730002,0.08655357,0.09825557};            
		openmc::Tabular ang_dist_25(cos_angles_25, ang_probabilities_25, 16, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_25);

		// Angular distribution for energies 101000.0 < E <= 105000.0            
		double cos_angles_26[14] = {-0.587785 ,-0.573576 ,-0.358368 ,-0.241922 ,-0.0348995, 0.0871557,
  0.390731 , 0.544639 , 0.656059 , 0.777146 , 0.882948 , 0.891007 ,
  0.945519 , 1.       };            
		double ang_probabilities_26[14] = {0.        ,0.07586149,0.06996225,0.06911099,0.06522965,0.06150699,
 0.06210504,0.06471355,0.06999222,0.07912969,0.08970733,0.08787334,
 0.09666731,0.10814015};            
		openmc::Tabular ang_dist_26(cos_angles_26, ang_probabilities_26, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_26);

		// Angular distribution for energies 105000.0 < E <= 109000.0            
		double cos_angles_27[14] = {-5.44639e-01,-5.29919e-01,-3.25568e-01,-2.07912e-01,-1.03634e-13,
  1.21869e-01, 4.06737e-01, 5.59193e-01, 6.56059e-01, 7.88011e-01,
  8.98794e-01, 9.06308e-01, 9.56305e-01, 1.00000e+00};            
		double ang_probabilities_27[14] = {0.        ,0.07638745,0.07046649,0.06945688,0.06540247,0.06163524,
 0.06220237,0.06483916,0.06908638,0.07910264,0.09054175,0.08849688,
 0.09669855,0.10568374};            
		openmc::Tabular ang_dist_27(cos_angles_27, ang_probabilities_27, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_27);

		// Angular distribution for energies 109000.0 < E <= 113000.0            
		double cos_angles_28[13] = {-0.5      ,-0.48481  ,-0.292372 ,-0.173648 , 0.0348995, 0.139173 ,
  0.422618 , 0.587785 , 0.669131 , 0.809017 , 0.920505 , 0.927184 ,
  1.       };            
		double ang_probabilities_28[13] = {0.        ,0.08468881,0.07821752,0.07691945,0.0722571 ,0.06831553,
 0.0686807 ,0.07204964,0.07610522,0.08817636,0.10139469,0.09923141,
 0.11396359};            
		openmc::Tabular ang_dist_28(cos_angles_28, ang_probabilities_28, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_28);

		// Angular distribution for energies 113000.0 < E <= 117000.0            
		double cos_angles_29[13] = {-0.469472,-0.45399 ,-0.241922,-0.139173, 0.052336, 0.173648, 0.438371,
  0.601815, 0.681998, 0.819152, 0.939693, 0.945519, 1.      };            
		double ang_probabilities_29[13] = {0.        ,0.08541497,0.07807145,0.07706139,0.07262776,0.06822233,
 0.06862837,0.07201777,0.07587575,0.08789904,0.10254658,0.10033661,
 0.11129797};            
		openmc::Tabular ang_dist_29(cos_angles_29, ang_probabilities_29, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_29);

		// Angular distribution for energies 117000.0 < E <= 121000.0            
		double cos_angles_30[13] = {-0.422618 ,-0.406737 ,-0.207912 ,-0.104528 , 0.0871557, 0.207912 ,
  0.45399  , 0.615661 , 0.694658 , 0.838671 , 0.956305 , 0.961262 ,
  1.       };            
		double ang_probabilities_30[13] = {0.        ,0.08552642,0.07833182,0.07719659,0.07257702,0.06814455,
 0.0685962 ,0.07200749,0.07567044,0.08860434,0.103481  ,0.1010719 ,
 0.10879224};            
		openmc::Tabular ang_dist_30(cos_angles_30, ang_probabilities_30, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_30);

		// Angular distribution for energies 121000.0 < E <= 125000.0            
		double cos_angles_31[14] = {-0.390731 ,-0.374607 ,-0.173648 ,-0.0697565, 0.121869 , 0.224951 ,
  0.469472 , 0.62932  , 0.707107 , 0.819152 , 0.882948 , 0.97437  ,
  0.978148 , 1.       };            
		double ang_probabilities_31[14] = {0.        ,0.07907455,0.07210064,0.07095447,0.06653509,0.06275258,
 0.06293864,0.06608313,0.06927278,0.07825809,0.08463025,0.09604509,
 0.09368943,0.09766525};            
		openmc::Tabular ang_dist_31(cos_angles_31, ang_probabilities_31, 14, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_31);

		// Angular distribution for energies 125000.0 < E <= 129000.0            
		double cos_angles_32[13] = {-0.358368 ,-0.34202  ,-0.139173 ,-0.0348995, 0.156434 , 0.258819 ,
  0.48481  , 0.642788 , 0.71934  , 0.848048 , 0.990268 , 0.992546 ,
  1.       };            
		double ang_probabilities_32[13] = {0.        ,0.08685504,0.07885084,0.07749197,0.07247059,0.06830873,
 0.06865771,0.07208898,0.0753938 ,0.08704963,0.1057376 ,0.10281479,
 0.10428031};            
		openmc::Tabular ang_dist_32(cos_angles_32, ang_probabilities_32, 13, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_32);

		// Angular distribution for energies 129000.0 < E <= 133000.0            
		double cos_angles_33[12] = {-3.25568e-01,-3.09017e-01,-1.04528e-01,-1.03634e-13, 1.73648e-01,
  2.92372e-01, 5.15038e-01, 6.69131e-01, 7.43145e-01, 7.98636e-01,
  8.74620e-01, 1.00000e+00};            
		double ang_probabilities_33[12] = {0.        ,0.09963201,0.09006608,0.08838479,0.08298802,0.07774118,
 0.07841301,0.0826255 ,0.08661488,0.09176267,0.10100565,0.12076621};            
		openmc::Tabular ang_dist_33(cos_angles_33, ang_probabilities_33, 12, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_33);

		// Angular distribution for energies 133000.0 < E <= 137000.0            
		double cos_angles_34[12] = {-0.275637 ,-0.258819 ,-0.0697565, 0.0174524, 0.207912 , 0.309017 ,
  0.529919 , 0.669131 , 0.75471  , 0.866025 , 0.93358  , 1.       };            
		double ang_probabilities_34[12] = {0.        ,0.09822235,0.08919659,0.0878688 ,0.08188316,0.07705196,
 0.07752192,0.0812301 ,0.08543107,0.09714355,0.1063419 ,0.1181086 };            
		openmc::Tabular ang_dist_34(cos_angles_34, ang_probabilities_34, 12, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_34);

		// Angular distribution for energies 137000.0 < E <= 141000.0            
		double cos_angles_35[12] = {-0.258819,-0.241922,-0.052336, 0.052336, 0.241922, 0.34202 , 0.544639,
  0.681998, 0.777146, 0.87462 , 0.945519, 1.      };            
		double ang_probabilities_35[12] = {0.        ,0.09956712,0.08992954,0.08790321,0.08164892,0.07686024,
 0.07750971,0.08118151,0.08604384,0.09656203,0.10642491,0.11636898};            
		openmc::Tabular ang_dist_35(cos_angles_35, ang_probabilities_35, 12, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_35);

		// Angular distribution for energies 141000.0 < E <= 145000.0            
		double cos_angles_36[12] = {-0.224951 ,-0.207912 ,-0.0174524, 0.0871557, 0.258819 , 0.358368 ,
  0.573576 , 0.694658 , 0.788011 , 0.87462  , 0.956305 , 1.       };            
		double ang_probabilities_36[12] = {0.        ,0.10032258,0.09027074,0.08814343,0.08223823,0.0772747 ,
 0.0778752 ,0.08138107,0.08607466,0.09515347,0.1067059 ,0.11456002};            
		openmc::Tabular ang_dist_36(cos_angles_36, ang_probabilities_36, 12, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_36);

		// Angular distribution for energies 145000.0 < E <= 149000.0            
		double cos_angles_37[11] = {-0.190809 ,-0.173648 , 0.0174524, 0.104528 , 0.292372 , 0.390731 ,
  0.587785 , 0.694658 , 0.798636 , 0.882948 , 1.       };            
		double ang_probabilities_37[11] = {0.        ,0.11314168,0.10144922,0.09955753,0.09209286,0.08658125,
 0.08747895,0.09081935,0.09645511,0.10621419,0.12620984};            
		openmc::Tabular ang_dist_37(cos_angles_37, ang_probabilities_37, 11, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_37);

		// Angular distribution for energies 149000.0 < E <= 153000.0            
		double cos_angles_38[10] = {-0.156434 ,-0.139173 , 0.0348995, 0.309017 , 0.406737 , 0.601815 ,
  0.707107 , 0.819152 , 0.891007 , 1.       };            
		double ang_probabilities_38[10] = {0.        ,0.12614598,0.11366978,0.10275183,0.09642558,0.09723557,
 0.10082774,0.10788426,0.11726057,0.13779869};            
		openmc::Tabular ang_dist_38(cos_angles_38, ang_probabilities_38, 10, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_38);

		// Angular distribution for energies 153000.0 < E <= 157000.0            
		double cos_angles_39[9] = {-0.121869 ,-0.104528 , 0.0697565, 0.173648 , 0.45399  , 0.642788 ,
  0.788011 , 0.87462  , 1.       };            
		double ang_probabilities_39[9] = {0.        ,0.1409708 ,0.12666073,0.12303131,0.10710356,0.10883074,
 0.11648173,0.12582061,0.15110052};            
		openmc::Tabular ang_dist_39(cos_angles_39, ang_probabilities_39, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_39);

		// Angular distribution for energies 157000.0 < E <= 161000.0            
		double cos_angles_40[9] = {-0.104528 ,-0.0871557, 0.104528 , 0.190809 , 0.469472 , 0.656059 ,
  0.798636 , 0.891007 , 1.       };            
		double ang_probabilities_40[9] = {0.        ,0.14278477,0.12652021,0.12374703,0.1070183 ,0.10872071,
 0.11630107,0.12631673,0.14859118};            
		openmc::Tabular ang_dist_40(cos_angles_40, ang_probabilities_40, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_40);

		// Angular distribution for energies 161000.0 < E <= 165000.0            
		double cos_angles_41[11] = {-0.0697565,-0.052336 , 0.121869 , 0.207912 , 0.390731 , 0.469472 ,
  0.5      , 0.681998 , 0.798636 , 0.891007 , 1.       };            
		double ang_probabilities_41[11] = {0.        ,0.11737365,0.10463055,0.10208892,0.09356804,0.0883305 ,
 0.08783638,0.08944939,0.09473891,0.10210032,0.11988333};            
		openmc::Tabular ang_dist_41(cos_angles_41, ang_probabilities_41, 11, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_41);

		// Angular distribution for energies 165000.0 < E <= 169000.0            
		double cos_angles_42[9] = {-0.052336 ,-0.0348995, 0.156434 , 0.241922 , 0.515038 , 0.694658 ,
  0.788011 , 0.898794 , 1.       };            
		double ang_probabilities_42[9] = {0.        ,0.14588619,0.12818157,0.12502481,0.10768936,0.10965007,
 0.11457653,0.12458345,0.14440802};            
		openmc::Tabular ang_dist_42(cos_angles_42, ang_probabilities_42, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_42);

		// Angular distribution for energies 169000.0 < E <= 173000.0            
		double cos_angles_43[10] = {-1.74524e-02,-1.03634e-13, 1.73648e-01, 2.58819e-01, 5.29919e-01,
  7.07107e-01, 7.77146e-01, 8.98794e-01, 9.45519e-01, 1.00000e+00};            
		double ang_probabilities_43[10] = {0.        ,0.12965766,0.1147045 ,0.11165132,0.09565826,0.09733951,
 0.10030115,0.10923638,0.11558915,0.12586206};            
		openmc::Tabular ang_dist_43(cos_angles_43, ang_probabilities_43, 10, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_43);

		// Angular distribution for energies 173000.0 < E <= 177000.0            
		double cos_angles_44[12] = {0.0174524,0.0348995,0.207912 ,0.292372 ,0.469472 ,0.529919 ,0.559193 ,
 0.71934  ,0.788011 ,0.906308 ,0.951057 ,1.       };            
		double ang_probabilities_44[12] = {0.        ,0.10866361,0.0959771 ,0.09333495,0.08488292,0.08077609,
 0.08014626,0.08157249,0.08390745,0.09118903,0.0960412 ,0.1035089 };            
		openmc::Tabular ang_dist_44(cos_angles_44, ang_probabilities_44, 12, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_44);

		// Angular distribution for energies 177000.0 < E <= 181000.0            
		double cos_angles_45[9] = {0.0348995,0.052336 ,0.224951 ,0.309017 ,0.573576 ,0.743145 ,0.788011 ,
 0.913545 ,1.       };            
		double ang_probabilities_45[9] = {0.        ,0.14913779,0.1309855 ,0.12719751,0.10856104,0.11071821,
 0.11274209,0.12305043,0.13760744};            
		openmc::Tabular ang_dist_45(cos_angles_45, ang_probabilities_45, 9, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_45);

		// Angular distribution for energies 181000.0 < E <= 185000.0            
		double cos_angles_46[8] = {0.052336 ,0.0697565,0.241922 ,0.325568 ,0.587785 ,0.798636 ,0.920505 ,
 1.       };            
		double ang_probabilities_46[8] = {0.        ,0.1698196 ,0.14835308,0.14371717,0.12206694,0.12643547,
 0.13775676,0.15185098};            
		openmc::Tabular ang_dist_46(cos_angles_46, ang_probabilities_46, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_46);

		// Angular distribution for energies 185000.0 < E <= 189000.0            
		double cos_angles_47[8] = {0.0871557,0.104528 ,0.275637 ,0.358368 ,0.615661 ,0.809017 ,0.927184 ,
 1.       };            
		double ang_probabilities_47[8] = {0.        ,0.17037004,0.14863335,0.14393218,0.1225169 ,0.12675411,
 0.13786294,0.14993048};            
		openmc::Tabular ang_dist_47(cos_angles_47, ang_probabilities_47, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_47);

		// Angular distribution for energies 189000.0 < E <= 193000.0            
		double cos_angles_48[8] = {0.104528,0.121869,0.292372,0.374607,0.62932 ,0.819152,0.927184,1.      };            
		double ang_probabilities_48[8] = {0.        ,0.17256464,0.14971655,0.14475159,0.12250328,0.12645259,
 0.13653413,0.14747721};            
		openmc::Tabular ang_dist_48(cos_angles_48, ang_probabilities_48, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_48);

		// Angular distribution for energies 193000.0 < E <= 197000.0            
		double cos_angles_49[8] = {0.139173,0.156434,0.325568,0.390731,0.642788,0.829038,0.920505,1.      };            
		double ang_probabilities_49[8] = {0.        ,0.17288882,0.1499369 ,0.14620632,0.12315334,0.12676227,
 0.13508628,0.14596608};            
		openmc::Tabular ang_dist_49(cos_angles_49, ang_probabilities_49, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_49);

		// Angular distribution for energies 197000.0 < E <= 201000.0            
		double cos_angles_50[8] = {0.156434,0.173648,0.34202 ,0.422618,0.656059,0.838671,0.913545,1.      };            
		double ang_probabilities_50[8] = {0.        ,0.1753757 ,0.1512267 ,0.14579941,0.12350536,0.1266871 ,
 0.13315182,0.14425391};            
		openmc::Tabular ang_dist_50(cos_angles_50, ang_probabilities_50, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_50);

		// Angular distribution for energies 201000.0 < E <= 205000.0            
		double cos_angles_51[8] = {0.173648,0.190809,0.358368,0.438371,0.681998,0.857167,0.920505,1.      };            
		double ang_probabilities_51[8] = {0.        ,0.1773376 ,0.15207334,0.1464095 ,0.12293759,0.12668378,
 0.13227514,0.14228306};            
		openmc::Tabular ang_dist_51(cos_angles_51, ang_probabilities_51, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_51);

		// Angular distribution for energies 205000.0 < E <= 209000.0            
		double cos_angles_52[8] = {0.190809,0.207912,0.374607,0.45399 ,0.694658,0.866025,0.920505,1.      };            
		double ang_probabilities_52[8] = {0.        ,0.17945929,0.15306427,0.14706528,0.12291405,0.12624806,
 0.13071609,0.14053295};            
		openmc::Tabular ang_dist_52(cos_angles_52, ang_probabilities_52, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_52);

		// Angular distribution for energies 209000.0 < E <= 213000.0            
		double cos_angles_53[6] = {0.224951,0.241922,0.406737,0.71934 ,0.882948,1.      };            
		double ang_probabilities_53[6] = {0.        ,0.24845413,0.21193547,0.17054017,0.17577423,0.193296  };            
		openmc::Tabular ang_dist_53(cos_angles_53, ang_probabilities_53, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_53);

		// Angular distribution for energies 213000.0 < E <= 217000.0            
		double cos_angles_54[6] = {0.241922,0.258819,0.422618,0.731354,0.898794,1.      };            
		double ang_probabilities_54[6] = {0.        ,0.25097648,0.21289749,0.17017119,0.17540296,0.19055188};            
		openmc::Tabular ang_dist_54(cos_angles_54, ang_probabilities_54, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_54);

		// Angular distribution for energies 217000.0 < E <= 221000.0            
		double cos_angles_55[6] = {0.258819,0.275637,0.438371,0.743145,0.906308,1.      };            
		double ang_probabilities_55[6] = {0.        ,0.25365802,0.21400191,0.17001129,0.17449562,0.18783316};            
		openmc::Tabular ang_dist_55(cos_angles_55, ang_probabilities_55, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_55);

		// Angular distribution for energies 221000.0 < E <= 225000.0            
		double cos_angles_56[7] = {0.275637,0.292372,0.390731,0.469472,0.766044,0.920505,1.      };            
		double ang_probabilities_56[7] = {0.        ,0.20909338,0.18693258,0.17323777,0.13786128,0.14194154,
 0.15093346};            
		openmc::Tabular ang_dist_56(cos_angles_56, ang_probabilities_56, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_56);

		// Angular distribution for energies 225000.0 < E <= 229000.0            
		double cos_angles_57[7] = {0.309017,0.325568,0.406737,0.48481 ,0.777146,0.927184,1.      };            
		double ang_probabilities_57[7] = {0.        ,0.20779316,0.18889912,0.17455219,0.13808511,0.14158691,
 0.14908351};            
		openmc::Tabular ang_dist_57(cos_angles_57, ang_probabilities_57, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_57);

		// Angular distribution for energies 229000.0 < E <= 233000.0            
		double cos_angles_58[8] = {0.325568,0.34202 ,0.422618,0.5     ,0.788011,0.819152,0.939693,1.      };            
		double ang_probabilities_58[8] = {0.        ,0.18436935,0.16715788,0.15402933,0.12122734,0.12040022,
 0.12389792,0.12891795};            
		openmc::Tabular ang_dist_58(cos_angles_58, ang_probabilities_58, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_58);

		// Angular distribution for energies 233000.0 < E <= 237000.0            
		double cos_angles_59[7] = {0.34202 ,0.358368,0.438371,0.515038,0.809017,0.945519,1.      };            
		double ang_probabilities_59[7] = {0.        ,0.21166634,0.19139667,0.17588555,0.13678805,0.1399805 ,
 0.14428289};            
		openmc::Tabular ang_dist_59(cos_angles_59, ang_probabilities_59, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_59);

		// Angular distribution for energies 237000.0 < E <= 241000.0            
		double cos_angles_60[7] = {0.358368,0.374607,0.469472,0.544639,0.819152,0.857167,1.      };            
		double ang_probabilities_60[7] = {0.        ,0.2155225 ,0.19073689,0.17570524,0.13780475,0.13688153,
 0.14334909};            
		openmc::Tabular ang_dist_60(cos_angles_60, ang_probabilities_60, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_60);

		// Angular distribution for energies 241000.0 < E <= 245000.0            
		double cos_angles_61[7] = {0.374607,0.390731,0.48481 ,0.559193,0.838671,0.866025,1.      };            
		double ang_probabilities_61[7] = {0.        ,0.21759256,0.19196615,0.1763391 ,0.1367107 ,0.13594814,
 0.14144335};            
		openmc::Tabular ang_dist_61(cos_angles_61, ang_probabilities_61, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_61);

		// Angular distribution for energies 245000.0 < E <= 249000.0            
		double cos_angles_62[7] = {0.406737,0.422618,0.5     ,0.573576,0.848048,0.882948,1.      };            
		double ang_probabilities_62[7] = {0.        ,0.21553719,0.19386121,0.17759446,0.13706526,0.13565115,
 0.14029072};            
		openmc::Tabular ang_dist_62(cos_angles_62, ang_probabilities_62, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_62);

		// Angular distribution for energies 249000.0 < E <= 253000.0            
		double cos_angles_63[7] = {0.422618,0.438371,0.515038,0.587785,0.866025,0.898794,1.      };            
		double ang_probabilities_63[7] = {0.        ,0.21739005,0.19501713,0.17818155,0.13588408,0.13476144,
 0.13876575};            
		openmc::Tabular ang_dist_63(cos_angles_63, ang_probabilities_63, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_63);

		// Angular distribution for energies 253000.0 < E <= 257000.0            
		double cos_angles_64[7] = {0.438371,0.45399 ,0.544639,0.615661,0.87462 ,0.906308,1.      };            
		double ang_probabilities_64[7] = {0.        ,0.22046689,0.19333193,0.1771478 ,0.1365494 ,0.13444015,
 0.13806383};            
		openmc::Tabular ang_dist_64(cos_angles_64, ang_probabilities_64, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_64);

		// Angular distribution for energies 257000.0 < E <= 261000.0            
		double cos_angles_65[7] = {0.45399 ,0.469472,0.559193,0.62932 ,0.891007,0.920505,1.      };            
		double ang_probabilities_65[7] = {0.        ,0.22241137,0.19444287,0.17767552,0.1354163 ,0.13346779,
 0.13658615};            
		openmc::Tabular ang_dist_65(cos_angles_65, ang_probabilities_65, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_65);

		// Angular distribution for energies 261000.0 < E <= 265000.0            
		double cos_angles_66[7] = {0.469472,0.48481 ,0.573576,0.642788,0.898794,0.93358 ,1.      };            
		double ang_probabilities_66[7] = {0.        ,0.22411912,0.19534396,0.17802526,0.13535499,0.13230091,
 0.13485576};            
		openmc::Tabular ang_dist_66(cos_angles_66, ang_probabilities_66, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_66);

		// Angular distribution for energies 265000.0 < E <= 269000.0            
		double cos_angles_67[8] = {0.48481 ,0.5     ,0.573576,0.642788,0.777146,0.927184,0.951057,1.      };            
		double ang_probabilities_67[8] = {0.        ,0.1946338 ,0.17282285,0.15635547,0.13463062,0.11395745,
 0.11296049,0.11463932};            
		openmc::Tabular ang_dist_67(cos_angles_67, ang_probabilities_67, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_67);

		// Angular distribution for energies 269000.0 < E <= 273000.0            
		double cos_angles_68[8] = {0.5     ,0.515038,0.587785,0.656059,0.788011,0.939693,0.965926,1.      };            
		double ang_probabilities_68[8] = {0.        ,0.19631344,0.17387996,0.1569504 ,0.1346479 ,0.11317859,
 0.11196448,0.11306523};            
		openmc::Tabular ang_dist_68(cos_angles_68, ang_probabilities_68, 8, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_68);

		// Angular distribution for energies 273000.0 < E <= 277000.0            
		double cos_angles_69[7] = {0.529919,0.544639,0.601815,0.669131,0.798636,0.951057,1.      };            
		double ang_probabilities_69[7] = {0.        ,0.21826272,0.19789475,0.17822726,0.15235802,0.12723976,
 0.1260175 };            
		openmc::Tabular ang_dist_69(cos_angles_69, ang_probabilities_69, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_69);

		// Angular distribution for energies 277000.0 < E <= 281000.0            
		double cos_angles_70[7] = {0.544639,0.559193,0.642788,0.71934 ,0.819152,0.961262,1.      };            
		double ang_probabilities_70[7] = {0.        ,0.22409533,0.19384849,0.17321063,0.15334693,0.12892902,
 0.12656961};            
		openmc::Tabular ang_dist_70(cos_angles_70, ang_probabilities_70, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_70);

		// Angular distribution for energies 281000.0 < E <= 285000.0            
		double cos_angles_71[7] = {0.559193,0.573576,0.656059,0.731354,0.848048,0.97437 ,1.      };            
		double ang_probabilities_71[7] = {0.        ,0.22651971,0.19539751,0.17403377,0.15032297,0.12811412,
 0.12561192};            
		openmc::Tabular ang_dist_71(cos_angles_71, ang_probabilities_71, 7, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_71);

		// Angular distribution for energies 285000.0 < E <= 289000.0            
		double cos_angles_72[6] = {0.573576,0.587785,0.669131,0.743145,0.848048,1.      };            
		double ang_probabilities_72[6] = {0.        ,0.26057165,0.22415352,0.19903589,0.17345474,0.14278421};            
		openmc::Tabular ang_dist_72(cos_angles_72, ang_probabilities_72, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_72);

		// Angular distribution for energies 289000.0 < E <= 293000.0            
		double cos_angles_73[6] = {0.587785,0.601815,0.681998,0.75471 ,0.866025,1.      };            
		double ang_probabilities_73[6] = {0.        ,0.26204922,0.22481844,0.19904814,0.17108117,0.14300302};            
		openmc::Tabular ang_dist_73(cos_angles_73, ang_probabilities_73, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_73);

		// Angular distribution for energies 293000.0 < E <= 297000.0            
		double cos_angles_74[6] = {0.601815,0.615661,0.707107,0.777146,0.882948,1.      };            
		double ang_probabilities_74[6] = {0.        ,0.26552121,0.22203861,0.19737317,0.17007841,0.1449886 };            
		openmc::Tabular ang_dist_74(cos_angles_74, ang_probabilities_74, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_74);

		// Angular distribution for energies 297000.0 < E <= 301000.0            
		double cos_angles_75[6] = {0.615661,0.62932 ,0.71934 ,0.788011,0.891007,1.      };            
		double ang_probabilities_75[6] = {0.        ,0.26628955,0.22202677,0.19678672,0.16926664,0.14563031};            
		openmc::Tabular ang_dist_75(cos_angles_75, ang_probabilities_75, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_75);

		// Angular distribution for energies 301000.0 < E <= 305000.0            
		double cos_angles_76[6] = {0.642788,0.656059,0.731354,0.798636,0.906308,1.      };            
		double ang_probabilities_76[6] = {0.        ,0.26201151,0.22417406,0.19815216,0.16826068,0.1474016 };            
		openmc::Tabular ang_dist_76(cos_angles_76, ang_probabilities_76, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_76);

		// Angular distribution for energies 305000.0 < E <= 309000.0            
		double cos_angles_77[6] = {0.656059,0.669131,0.743145,0.819152,0.920505,1.      };            
		double ang_probabilities_77[6] = {0.        ,0.26408678,0.22541588,0.19546093,0.1666721 ,0.14836431};            
		openmc::Tabular ang_dist_77(cos_angles_77, ang_probabilities_77, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_77);

		// Angular distribution for energies 309000.0 < E <= 313000.0            
		double cos_angles_78[6] = {0.669131,0.681998,0.75471 ,0.829038,0.927184,1.      };            
		double ang_probabilities_78[6] = {0.        ,0.26482755,0.22553491,0.19498628,0.16610032,0.14855094};            
		openmc::Tabular ang_dist_78(cos_angles_78, ang_probabilities_78, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_78);

		// Angular distribution for energies 313000.0 < E <= 317000.0            
		double cos_angles_79[6] = {0.681998,0.694658,0.766044,0.838671,0.939693,1.      };            
		double ang_probabilities_79[6] = {0.        ,0.26594319,0.22599384,0.19486268,0.16413905,0.14906124};            
		openmc::Tabular ang_dist_79(cos_angles_79, ang_probabilities_79, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_79);

		// Angular distribution for energies 317000.0 < E <= 321000.0            
		double cos_angles_80[6] = {0.694658,0.707107,0.777146,0.848048,0.951057,1.      };            
		double ang_probabilities_80[6] = {0.        ,0.26695154,0.22638426,0.19473714,0.16232596,0.1496011 };            
		openmc::Tabular ang_dist_80(cos_angles_80, ang_probabilities_80, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_80);

		// Angular distribution for energies 321000.0 < E <= 325000.0            
		double cos_angles_81[5] = {0.71934 ,0.731354,0.798636,0.866025,1.      };            
		double ang_probabilities_81[5] = {0.        ,0.31605877,0.26897518,0.23245643,0.18250962};            
		openmc::Tabular ang_dist_81(cos_angles_81, ang_probabilities_81, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_81);

		// Angular distribution for energies 325000.0 < E <= 329000.0            
		double cos_angles_82[5] = {0.731354,0.743145,0.809017,0.87462 ,1.      };            
		double ang_probabilities_82[5] = {0.        ,0.31644133,0.26882205,0.23186236,0.18287426};            
		openmc::Tabular ang_dist_82(cos_angles_82, ang_probabilities_82, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_82);

		// Angular distribution for energies 329000.0 < E <= 333000.0            
		double cos_angles_83[5] = {0.743145,0.75471 ,0.819152,0.882948,1.      };            
		double ang_probabilities_83[5] = {0.        ,0.31670505,0.26860723,0.23130016,0.18338756};            
		openmc::Tabular ang_dist_83(cos_angles_83, ang_probabilities_83, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_83);

		// Angular distribution for energies 333000.0 < E <= 337000.0            
		double cos_angles_84[5] = {0.75471 ,0.766044,0.829038,0.891007,1.      };            
		double ang_probabilities_84[5] = {0.        ,0.31678898,0.26828394,0.23072714,0.18419994};            
		openmc::Tabular ang_dist_84(cos_angles_84, ang_probabilities_84, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_84);

		// Angular distribution for energies 337000.0 < E <= 341000.0            
		double cos_angles_85[5] = {0.777146,0.788011,0.848048,0.906308,1.      };            
		double ang_probabilities_85[5] = {0.        ,0.31344735,0.26665355,0.23057325,0.18932584};            
		openmc::Tabular ang_dist_85(cos_angles_85, ang_probabilities_85, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_85);

		// Angular distribution for energies 341000.0 < E <= 345000.0            
		double cos_angles_86[6] = {0.788011,0.798636,0.857167,0.913545,0.951057,1.      };            
		double ang_probabilities_86[6] = {0.        ,0.25856661,0.21972786,0.18987763,0.17407385,0.15775405};            
		openmc::Tabular ang_dist_86(cos_angles_86, ang_probabilities_86, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_86);

		// Angular distribution for energies 345000.0 < E <= 349000.0            
		double cos_angles_87[6] = {0.798636,0.809017,0.866025,0.920505,0.961262,1.      };            
		double ang_probabilities_87[6] = {0.        ,0.25901958,0.21992105,0.18999321,0.17199055,0.15907561};            
		openmc::Tabular ang_dist_87(cos_angles_87, ang_probabilities_87, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_87);

		// Angular distribution for energies 349000.0 < E <= 353000.0            
		double cos_angles_88[6] = {0.809017,0.819152,0.87462 ,0.920505,0.965926,1.      };            
		double ang_probabilities_88[6] = {0.        ,0.25812962,0.21902605,0.19269025,0.17114349,0.15901059};            
		openmc::Tabular ang_dist_88(cos_angles_88, ang_probabilities_88, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_88);

		// Angular distribution for energies 353000.0 < E <= 357000.0            
		double cos_angles_89[6] = {0.829038,0.838671,0.882948,0.927184,0.965926,1.      };            
		double ang_probabilities_89[6] = {0.        ,0.25187235,0.22010882,0.19367849,0.17405776,0.16028259};            
		openmc::Tabular ang_dist_89(cos_angles_89, ang_probabilities_89, 6, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_89);

		// Angular distribution for energies 357000.0 < E <= 361000.0            
		double cos_angles_90[5] = {0.838671,0.848048,0.891007,0.927184,1.      };            
		double ang_probabilities_90[5] = {0.        ,0.30327729,0.26500638,0.23770558,0.19401075};            
		openmc::Tabular ang_dist_90(cos_angles_90, ang_probabilities_90, 5, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_90);

		// Angular distribution for energies 361000.0 < E <= 365000.0            
		double cos_angles_91[4] = {0.857167,0.866025,0.93358 ,1.      };            
		double ang_probabilities_91[4] = {0.        ,0.40462479,0.32666459,0.26871062};            
		openmc::Tabular ang_dist_91(cos_angles_91, ang_probabilities_91, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_91);

		// Angular distribution for energies 365000.0 < E <= 369000.0            
		double cos_angles_92[4] = {0.866025,0.87462 ,0.939693,1.      };            
		double ang_probabilities_92[4] = {0.        ,0.40329018,0.32593745,0.27077238};            
		openmc::Tabular ang_dist_92(cos_angles_92, ang_probabilities_92, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_92);

		// Angular distribution for energies 369000.0 < E <= 373000.0            
		double cos_angles_93[4] = {0.882948,0.891007,0.945519,1.      };            
		double ang_probabilities_93[4] = {0.        ,0.39503884,0.32876425,0.27619691};            
		openmc::Tabular ang_dist_93(cos_angles_93, ang_probabilities_93, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_93);

		// Angular distribution for energies 373000.0 < E <= 377000.0            
		double cos_angles_94[4] = {0.891007,0.898794,0.951057,1.      };            
		double ang_probabilities_94[4] = {0.        ,0.39328717,0.32793596,0.27877686};            
		openmc::Tabular ang_dist_94(cos_angles_94, ang_probabilities_94, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_94);

		// Angular distribution for energies 377000.0 < E <= 381000.0            
		double cos_angles_95[4] = {0.906308,0.913545,0.956305,1.      };            
		double ang_probabilities_95[4] = {0.        ,0.38515303,0.3304968 ,0.28435018};            
		openmc::Tabular ang_dist_95(cos_angles_95, ang_probabilities_95, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_95);

		// Angular distribution for energies 381000.0 < E <= 385000.0            
		double cos_angles_96[4] = {0.920505,0.927184,0.965926,1.      };            
		double ang_probabilities_96[4] = {0.        ,0.37945335,0.32907618,0.29147047};            
		openmc::Tabular ang_dist_96(cos_angles_96, ang_probabilities_96, 4, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_96);

		// Angular distribution for energies 385000.0 < E <= 389000.0            
		double cos_angles_97[3] = {0.93358 ,0.939693,1.      };            
		double ang_probabilities_97[3] = {0.       ,0.5561331,0.4438669};            
		openmc::Tabular ang_dist_97(cos_angles_97, ang_probabilities_97, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_97);

		// Angular distribution for energies 389000.0 < E <= 393000.0            
		double cos_angles_98[3] = {0.945519,0.951057,1.      };            
		double ang_probabilities_98[3] = {0.        ,0.54705888,0.45294112};            
		openmc::Tabular ang_dist_98(cos_angles_98, ang_probabilities_98, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_98);

		// Angular distribution for energies 393000.0 < E <= 397000.0            
		double cos_angles_99[3] = {0.961262,0.965926,1.      };            
		double ang_probabilities_99[3] = {0.        ,0.53379138,0.46620862};            
		openmc::Tabular ang_dist_99(cos_angles_99, ang_probabilities_99, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_99);

		// Angular distribution for energies 397000.0 < E <= 401000.0            
		double cos_angles_100[3] = {0.970296,0.97437 ,1.      };            
		double ang_probabilities_100[3] = {0.        ,0.52618068,0.47381932};            
		openmc::Tabular ang_dist_100(cos_angles_100, ang_probabilities_100, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_100);

		// Angular distribution for energies 401000.0 < E <= 405000.0            
		double cos_angles_101[3] = {0.984808,0.987688,1.      };            
		double ang_probabilities_101[3] = {0.        ,0.51292069,0.48707931};            
		openmc::Tabular ang_dist_101(cos_angles_101, ang_probabilities_101, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_101);

		// Angular distribution for energies 405000.0 < E <= 408000.0            
		double cos_angles_102[3] = {0.994522,0.996195,1.      };            
		double ang_probabilities_102[3] = {0.        ,0.50406993,0.49593007};            
		openmc::Tabular ang_dist_102(cos_angles_102, ang_probabilities_102, 3, openmc::Interpolation::lin_lin);            
		ang_dists.push_back(ang_dist_102);

		// Choose angular distribution depending on sampled energy    
		for (int n = 0; n < 102; n++) {    
			if (energy < edges[n]) {     
				mu = ang_dists[n].sample(seed);    
				break;
			}
		}

		// Convert sampled mu to angle    
		theta = std::acos(mu);    
		// Sample phi in range [0,2pi];    
		phi = 2.0 * M_PI * openmc::prn(seed);    

		// Set directional vector    
		particle.u = {std::sin(theta)*std::cos(phi), std::sin(theta)*std::sin(phi), mu};

		// Sample particle starting position
		openmc::PowerLaw r_dist(0, 5, 1);    
		pos_r = r_dist.sample(seed);    
		pos_ang = 2.0 * M_PI * openmc::prn(seed);    
		// Set position of particle    
		particle.r = {pos_r*std::cos(pos_ang), pos_r*std::sin(pos_ang) - 42, 0.0};

		// Return particle    
		return particle;    
	}    
};

// Function to create unique pointer to an instance of this class when generated via a plugin call using dlopen/dlsym    
extern "C" std::unique_ptr<Li_source> openmc_create_source(std::string parameters) {    
	return std::make_unique<Li_source>();    
}